table '01 XER_TASK'
	lineageTag: de86e8cb-d782-4301-95e1-09a8fd150627

	column task_type
		dataType: string
		lineageTag: f1565957-af11-4f1e-8524-207541bcd9c3
		summarizeBy: none
		sourceColumn: task_type

		annotation SummarizationSetBy = Automatic

	column status_code
		dataType: string
		lineageTag: 6f1c76d3-7397-4917-8e89-0541d93a3aa6
		summarizeBy: none
		sourceColumn: status_code

		annotation SummarizationSetBy = Automatic

	column task_code
		dataType: string
		lineageTag: 53c1cd6d-c886-4639-9ef2-2a56c751dd9c
		summarizeBy: none
		sourceColumn: task_code

		annotation SummarizationSetBy = Automatic

	column task_name
		dataType: string
		lineageTag: 958a1112-311f-4220-a612-aed548fd7d7c
		summarizeBy: none
		sourceColumn: task_name

		annotation SummarizationSetBy = Automatic

	column cstr_type
		dataType: string
		lineageTag: 1aa455af-ff12-4d85-a3af-9305c30ee911
		summarizeBy: none
		sourceColumn: cstr_type

		annotation SummarizationSetBy = Automatic

	column driving_path_flag
		dataType: string
		lineageTag: df8c5746-e757-44e2-a1bd-1d48af8bc8d3
		summarizeBy: none
		sourceColumn: driving_path_flag

		annotation SummarizationSetBy = Automatic

	column StatusCategory =
			
			IF(
			    '01 XER_TASK'[status_code] = "Complete",
			    "Complete",
			    "Not Complete"
			)
		lineageTag: 4143997f-d77d-4c87-9b34-0e4dc77610e3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CriticalStatus = ```
			
			VAR TaskStatus = TRIM(UPPER('01 XER_TASK'[status_code]))
			VAR FloatValue = '01 XER_TASK'[total_float]
			RETURN
			    IF(
			        TaskStatus <> "COMPLETE",
			        SWITCH(
			            TRUE(),
			            FloatValue <= 0, "Critical",
			            FloatValue > 0 && FloatValue <= 10, "Near Critical",
			            "Non-Critical"
			        ),
			        BLANK()
			    )
			
			```
		lineageTag: d8c504df-6a4d-49ad-9b83-1c8b123677b6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column FinishDateCategory = ```
			
			IF(
			   '01 XER_TASK'[status_code] <> "Complete",
			    VAR StartDate = '01 XER_TASK'[Finish]
			    VAR DataDate = '01 XER_TASK'[data_date]
			    VAR MonthsDifference = 
			        DATEDIFF(DataDate, StartDate, MONTH) + 
			        IF(DAY(StartDate) < DAY(DataDate), -1, 0)
			    RETURN
			        SWITCH(
			            TRUE(),
			            StartDate < DataDate, "Outside Range",
			            MonthsDifference < 1, " <1 Month",
			            MonthsDifference >= 1 && MonthsDifference < 3, " 1-3 Months",
			            MonthsDifference >= 3 && MonthsDifference < 6, " 3-6 Months",
			            MonthsDifference >= 6, ">6 Months",
			            BLANK()
			        ),
			    BLANK()
			)
			
			```
		lineageTag: b634f4d2-0ad4-4833-b622-257f56d60210
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StartDateCategory = ```
			
			IF(
			    // Only proceed if task_type is "TT_Task" and Activity_Status is "Not Started"
			   '01 XER_TASK'[status_code] = "Not Started",
			    
			    // Define variables
			    VAR StartDate = '01 XER_TASK'[Start]
			    VAR DataDate = '01 XER_TASK'[data_date]
			    VAR MonthsDifference = 
			        DATEDIFF(DataDate, StartDate, MONTH) + 
			        IF(DAY(StartDate) < DAY(DataDate), -1, 0)
			    
			    // Return the category based on MonthsDifference
			    RETURN
			        SWITCH(
			            TRUE(),
			            StartDate < DataDate, "Outside Range",
			            MonthsDifference < 1, " <1 Month",
			            MonthsDifference >= 1 && MonthsDifference < 3, " 1-3 Months",
			            MonthsDifference >= 3 && MonthsDifference < 6, " 3-6 Months",
			            MonthsDifference >= 6, ">6 Months",
			            BLANK()
			        ),
			    
			    // If conditions are not met, return BLANK()
			    BLANK()
			)
			```
		lineageTag: b718f299-5eee-4a98-9cc9-369593fb4096
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'No Predecessor' = if(CALCULATE(COUNTA('06 XER_PREDECESSOR'[pred_task_id_key]))=BLANK(),1,0)
		formatString: 0
		lineageTag: a09ffef3-83b6-400e-bfcb-d129f64a7cdd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column act_end_date
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: b1c39a59-0c64-4b03-bf09-077f8c4de963
		summarizeBy: none
		sourceColumn: act_end_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Float Category' = ```
			
			IF(
			    '01 XER_TASK'[status_code] = "Complete",
			    "Complete",
			    SWITCH(
			        TRUE(),
			        '01 XER_TASK'[total_float] < 0, " Float < 0",
			        '01 XER_TASK'[total_float] >= 0 && '01 XER_TASK'[total_float] <= 10, "0 ≤ Float ≤ 10",
			        '01 XER_TASK'[total_float] > 10 && '01 XER_TASK'[total_float] <= 30, "10 < Float ≤ 30",
			        '01 XER_TASK'[total_float] > 30 && '01 XER_TASK'[total_float] <= 50, "30 < Float ≤ 50",
			        '01 XER_TASK'[total_float] > 50, "50 < Float",
			        "Other Incomplete"
			    )
			)
			
			```
		lineageTag: a888ea7c-93cc-413b-a691-f95b0875b92e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column TaskType_Classified = ```
			
			SWITCH(
			    TRUE(),
			    '01 XER_TASK'[task_type] = "TT_Task", "Activity",
			    '01 XER_TASK'[task_type] = "TT_Rsrc", "Activity",
			    '01 XER_TASK'[task_type] = "TT_FinMile", "Milestone",
			    '01 XER_TASK'[task_type] = "TT_Mile", "Milestone",
			    '01 XER_TASK'[task_type] = "TT_LOE", "Level Of Effort",
			    '01 XER_TASK'[task_type] = "TT_WBS", "WBS Summary",
			    "Other"
			)
			
			```
		lineageTag: dfc59af2-9eae-4347-9cd7-31a2e45af94a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column wbs_id_key
		dataType: string
		lineageTag: 0fdde693-247e-4f91-aed7-fb733134d297
		summarizeBy: none
		sourceColumn: wbs_id_key

		annotation SummarizationSetBy = Automatic

	column task_id_key
		dataType: string
		lineageTag: a7f183c6-8fe9-422c-8ae7-26f32fcfcbc6
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column PreviousMonthFinishVarianceCategory = ```
			
			    SWITCH(
			        TRUE(),
			        '01 XER_TASK'[Finish_Variance_Previous_Month] = 0, "   No Variance",
			        '01 XER_TASK'[Finish_Variance_Previous_Month] > 0 && '01 XER_TASK'[Finish_Variance_Previous_Month] < 21, " <1 Month",
			        '01 XER_TASK'[Finish_Variance_Previous_Month] >= 21 && '01 XER_TASK'[Finish_Variance_Previous_Month] < 63, " 1-3 Months",
			        '01 XER_TASK'[Finish_Variance_Previous_Month] >= 63 && '01 XER_TASK'[Finish_Variance_Previous_Month] < 126, " 3-6 Months",
			        '01 XER_TASK'[Finish_Variance_Previous_Month] >= 126, ">6 Months",
			        '01 XER_TASK'[Finish_Variance_Previous_Month] < 0, "  Ahead",
			        BLANK()
			    )
			 
			```
		lineageTag: 239ae7b8-fd36-4e68-8b94-1e5eaaa1537a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Remaining Duration Category' =
			
			IF(
			    '01 XER_TASK'[status_code] = "Complete",
			    "Complete",
			    SWITCH(
			        TRUE(),
			        '01 XER_TASK'[remaining_duration] > 0 && '01 XER_TASK'[remaining_duration] <= 10, "0 < Dur. ≤ 10",
			        '01 XER_TASK'[remaining_duration] > 10 && '01 XER_TASK'[remaining_duration] <= 20, "10 < Dur. ≤ 20",
			        '01 XER_TASK'[remaining_duration] > 20 && '01 XER_TASK'[remaining_duration] <= 30, "20 < Dur. ≤ 30",
			        '01 XER_TASK'[remaining_duration] > 30 && '01 XER_TASK'[remaining_duration] <= 44, "30 < Dur. ≤ 44",
			        '01 XER_TASK'[remaining_duration] > 44, "44 < Dur.",
			        "Other Incomplete"
			    )
			)
		lineageTag: a172b330-82a0-414d-a753-ef805e9bc7e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column early_end_date
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: af2b83ec-de7f-4396-abe4-4caab4e3aeab
		summarizeBy: none
		sourceColumn: early_end_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column late_end_date
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 635f5342-290f-49cf-af8f-43babd552399
		summarizeBy: none
		sourceColumn: late_end_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_id_key
		dataType: string
		lineageTag: 52ddaef5-f47e-4b65-babd-448416f76212
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	column calendar_id_key
		dataType: string
		lineageTag: f0b65635-7f8a-410a-b176-5ea20f7d8301
		summarizeBy: none
		sourceColumn: calendar_id_key

		annotation SummarizationSetBy = Automatic

	column PreviousMonthStartVarianceCategory = ```
			
			    SWITCH(
			        TRUE(),
			        '01 XER_TASK'[Start_Variance_Previous_Month] = 0, "   No Variance",
			        '01 XER_TASK'[Start_Variance_Previous_Month] > 0 && '01 XER_TASK'[Start_Variance_Previous_Month] < 21, " <1 Month",
			        '01 XER_TASK'[Start_Variance_Previous_Month] >= 21 && '01 XER_TASK'[Start_Variance_Previous_Month] < 63, " 1-3 Months",
			        '01 XER_TASK'[Start_Variance_Previous_Month] >= 63 && '01 XER_TASK'[Start_Variance_Previous_Month] < 126, " 3-6 Months",
			        '01 XER_TASK'[Start_Variance_Previous_Month] >= 126, ">6 Months",
			        '01 XER_TASK'[Start_Variance_Previous_Month] < 0, "  Ahead",
			        BLANK()
			    )
			```
		lineageTag: b0f3aa18-1852-47d3-a513-3e54e95aab3d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column early_start_date
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 86180d61-b856-462b-b1df-f06c59c73035
		summarizeBy: none
		sourceColumn: early_start_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'No Successor' =
			IF(
			    CALCULATE(
			        COUNTROWS('06 XER_PREDECESSOR'),
			        FILTER(
			            '06 XER_PREDECESSOR',
			            '06 XER_PREDECESSOR'[pred_task_id_key] = '01 XER_TASK'[task_id_key]
			        )
			    ) = BLANK(),
			    1,
			    0
			)
		formatString: 0
		lineageTag: 59509a72-dfcd-40eb-ac1b-408f4ef6184c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Effective_Late_End =
			
			IF(
			    '01 XER_TASK'[status_code] = "Complete",
			    '01 XER_TASK'[Finish],
			    '01 XER_TASK'[late_end_date]
			)
		formatString: dd/mm/yy
		lineageTag: ea9955ee-a9e5-433f-96eb-fbe80c35b281
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Effective_Early_End =
			
			IF(
			    '01 XER_TASK'[status_code] = "Complete",
			    '01 XER_TASK'[Finish],
			    '01 XER_TASK'[early_end_date]
			)
		formatString: dd/mm/yy
		lineageTag: 6e83a192-10a1-43a3-825c-df94ace771ff
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Calendar = related('10 XER_CALENDARS'[clndr_name])
		lineageTag: 715710dd-9060-483d-bbe5-8e91a64ca32e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Start
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b0646acd-dd4e-46fe-9f1a-3dc024af32b1
		summarizeBy: none
		sourceColumn: Start

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Finish
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 8694ef00-cde3-40e9-bbed-d0766f0a9530
		summarizeBy: none
		sourceColumn: Finish

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column id_name
		dataType: string
		lineageTag: d0dc52e6-6090-487c-872f-32eb17da22ba
		summarizeBy: none
		sourceColumn: id_name

		annotation SummarizationSetBy = Automatic

	column total_float
		dataType: double
		lineageTag: ef9db39d-29a7-43b4-8108-47bb512bfba8
		summarizeBy: sum
		sourceColumn: total_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column free_float
		dataType: double
		lineageTag: e7052c2c-352e-4627-8f78-216aad769f19
		summarizeBy: sum
		sourceColumn: free_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column data_date
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: d4cde42b-ee39-48e2-8855-1de90e4b9dbf
		summarizeBy: none
		sourceColumn: data_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column filename
		dataType: string
		lineageTag: fb75265e-1ba1-43f3-8ec8-c9c0d17f3396
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		lineageTag: 2998c837-2a83-4749-8ef4-5b80c161c3cf
		summarizeBy: none
		sourceColumn: ProjectName

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99377e12-b3cb-4484-8650-e3e81f5b3f1c
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProjectCode
		dataType: string
		lineageTag: fbbe2e5e-d874-421d-86b8-5f4a2a7e2b27
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column remaining_duration
		dataType: double
		lineageTag: 699a859d-06c4-433c-b859-48a4f23b1d4f
		summarizeBy: sum
		sourceColumn: remaining_duration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column monthupdate
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: d0999a4f-5e63-4b8a-9a35-3ff4d279647b
		summarizeBy: none
		sourceColumn: monthupdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Finish_Variance_Previous_Month
		dataType: int64
		formatString: 0
		lineageTag: 40bdc0d3-a016-4c81-a60a-154fdd803918
		summarizeBy: none
		sourceColumn: Finish_Variance_Previous_Month

		annotation SummarizationSetBy = User

	column Driven_DataDate
		dataType: string
		lineageTag: 94225685-becc-4744-a625-f9973e146094
		summarizeBy: none
		sourceColumn: Driven_DataDate

		annotation SummarizationSetBy = Automatic

	column Variance_Finish_BL
		dataType: int64
		formatString: 0
		lineageTag: 0e8adf17-4283-49ba-8ca9-5f48c7067f76
		summarizeBy: sum
		sourceColumn: Variance_Finish_BL

		annotation SummarizationSetBy = Automatic

	column Start_Variance_Previous_Month
		dataType: int64
		formatString: 0
		lineageTag: cab1bd4a-03d4-4599-ad13-bfcc37c0d6ac
		summarizeBy: sum
		sourceColumn: Start_Variance_Previous_Month

		annotation SummarizationSetBy = Automatic

	column PreviousDataDate
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 53e4dfbc-8348-4392-8f3b-d2ca94275449
		summarizeBy: none
		sourceColumn: PreviousDataDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Baseline Finish'
		dataType: dateTime
		formatString: General Date
		lineageTag: f766f67d-ef58-428b-93f2-0cfa8d7666f6
		summarizeBy: none
		sourceColumn: Baseline Finish

		annotation SummarizationSetBy = Automatic

	column 'Baseline Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3aa47f43-4c1c-4cd2-8dfd-726e34d2ee59
		summarizeBy: none
		sourceColumn: Baseline Start

		annotation SummarizationSetBy = Automatic

	column 'Previous Month Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: 9217729f-0c71-458c-ae7a-dd2067bf4680
		summarizeBy: none
		sourceColumn: Previous Month Start

		annotation SummarizationSetBy = Automatic

	column 'Previous Month Finish'
		dataType: dateTime
		formatString: General Date
		lineageTag: f431186c-1d71-4c00-ae19-a40b299fd25b
		summarizeBy: none
		sourceColumn: Previous Month Finish

		annotation SummarizationSetBy = Automatic

	column 'Planned Not Completed Last Period'
		dataType: int64
		formatString: 0
		lineageTag: a1b2b276-de0b-4db1-a01e-ca1518214ae7
		summarizeBy: sum
		sourceColumn: Planned Not Completed Last Period

		annotation SummarizationSetBy = Automatic

	column 'Previous Remaining Working Days'
		dataType: double
		lineageTag: 0d5688df-858b-47c4-b611-da391cd42339
		summarizeBy: sum
		sourceColumn: Previous Remaining Working Days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Planned Last Period'
		dataType: int64
		formatString: 0
		lineageTag: 1246d0fa-144e-45e3-a4be-b51c8dde9179
		summarizeBy: sum
		sourceColumn: Planned Last Period

		annotation SummarizationSetBy = Automatic

	column 'Completed Last Period'
		dataType: int64
		formatString: 0
		lineageTag: 1d60c121-12dd-44a2-9876-5ba65039def5
		summarizeBy: sum
		sourceColumn: Completed Last Period

		annotation SummarizationSetBy = Automatic

	column 'Completed of Planned Last Period'
		dataType: int64
		formatString: 0
		lineageTag: 60febfab-c39f-4931-a6d3-29287a9197fd
		summarizeBy: sum
		sourceColumn: Completed of Planned Last Period

		annotation SummarizationSetBy = Automatic

	column 'Baseline Effective_Early_End'
		dataType: dateTime
		formatString: General Date
		lineageTag: 4d3bd24f-7907-499e-a5c1-049c9388da8d
		summarizeBy: none
		sourceColumn: Baseline Effective_Early_End

		annotation SummarizationSetBy = Automatic

	column 'Baseline Effective_Late_End'
		dataType: dateTime
		formatString: General Date
		lineageTag: 471edb92-8d5e-478d-856c-18a7dd59e025
		summarizeBy: none
		sourceColumn: Baseline Effective_Late_End

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Baseline Finish'
		dataType: dateTime
		formatString: General Date
		lineageTag: f1dfb3c8-7218-4927-a317-c92e7cd29f43
		summarizeBy: none
		sourceColumn: Adjusted Baseline Finish

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Baseline Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: dda1179c-0bfc-47df-aaef-f3c422979956
		summarizeBy: none
		sourceColumn: Adjusted Baseline Start

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Baseline Source Month'
		dataType: dateTime
		formatString: General Date
		lineageTag: 161ff24c-74bf-4180-938b-18010505da4e
		summarizeBy: none
		sourceColumn: Adjusted Baseline Source Month

		annotation SummarizationSetBy = Automatic

	column 'Adjusted Baseline Source'
		dataType: string
		lineageTag: 507f4253-f171-4828-9bdb-db511c4ea777
		summarizeBy: none
		sourceColumn: Adjusted Baseline Source

		annotation SummarizationSetBy = Automatic

	partition '01 XER_TASK' = m
		mode: import
		queryGroup: XER
		source =
				let
				    fnParseFileName = (fileName as nullable text) as record =>
				        let
				            SafeFileName = if fileName = null then null else Text.Trim(fileName),
				
				            Prefix =
				                if SafeFileName <> null and Text.Contains(SafeFileName, "_") then
				                    Text.BeforeDelimiter(SafeFileName, "_")
				                else
				                    SafeFileName,
				
				            PrefixParts =
				                if Prefix <> null then
				                    Text.Split(Prefix, "-")
				                else
				                    {},
				
				            ProjectCode =
				                if SafeFileName <> null and Text.Contains(SafeFileName, "-") and List.Count(PrefixParts) >= 1 then
				                    PrefixParts{0}
				                else
				                    null,
				
				            ProgType =
				                if List.Count(PrefixParts) >= 2 then
				                    PrefixParts{1}
				                else
				                    null,
				
				            CPart =
				                if List.Count(PrefixParts) >= 3 then
				                    PrefixParts{2}
				                else
				                    null,
				
				            IsBL =
				                CPart <> null and Text.StartsWith(CPart, "BL"),
				
				            UpdateDate =
				                if CPart = null or CPart = "" or IsBL then
				                    null
				                else
				                    let
				                        P1 = try Number.FromText(Text.Start(CPart, 2)) otherwise null,
				                        P2 = try Number.FromText(Text.End(CPart, 2)) otherwise null,
				                        Yr = if P1 = null or P2 = null then null else if P2 > 12 then P2 else P1,
				                        Mo = if P1 = null or P2 = null then null else if P2 > 12 then P1 else P2
				                    in
				                        if Yr = null or Mo = null or Mo < 1 or Mo > 12 then
				                            null
				                        else
				                            Date.EndOfMonth(#date(2000 + Yr, Mo, 1))
				        in
				            [
				                ProjectCode = ProjectCode,
				                UpdateDate = UpdateDate,
				                _IsBL = IsBL,
				                _ProgType = ProgType
				            ],
				
				    // Robust date parser: handles null, native date/datetime/datetimezone,
				    // and text in several common Athena output formats. Culture-independent.
				    fnToDate = (value) as nullable date =>
				        if value = null then
				            null
				        else if Value.Is(value, type date) then
				            value
				        else if Value.Is(value, type datetime) or Value.Is(value, type datetimezone) then
				            try Date.From(value) otherwise null
				        else if Value.Is(value, type text) then
				            let
				                trimmed = Text.Trim(value),
				                // Athena timestamps commonly arrive as "yyyy-MM-dd HH:mm:ss[.fff]"
				                // or "yyyy-MM-ddTHH:mm:ss[Z]" — first 10 chars are the date part.
				                datePart =
				                    if Text.Length(trimmed) >= 10 then Text.Start(trimmed, 10) else trimmed,
				                parsed =
				                    try Date.FromText(datePart, [Format = "yyyy-MM-dd", Culture = "en-US"])
				                    otherwise try Date.FromText(datePart, [Format = "yyyy/MM/dd", Culture = "en-US"])
				                    otherwise try Date.From(trimmed)
				                    otherwise null
				            in
				                parsed
				        else
				            try Date.From(value) otherwise null,
				
				    SourceRaw =
				        Value.NativeQuery(
				            AthenaDB,
				            Text.Combine(
				                {
				                    AthenaScopeSql,
				                    ", task_raw AS (",
				                    "SELECT ROW_NUMBER() OVER (ORDER BY t.""filename"", t.""task_id_key"", t.""task_code"", t.""start"", t.""finish"", t.""data_date"") AS task_row_id,",
				                    "t.""status_code"" AS status_code, t.""task_code"" AS task_code, TRY_CAST(t.""total_float"" AS DOUBLE) AS total_float, t.""task_type"" AS task_type,",
				                    "t.""id_name"" AS id_name, TRY_CAST(SUBSTR(CAST(t.""early_start_date"" AS VARCHAR), 1, 10) AS DATE) AS early_start_date, t.""calendar_id_key"" AS calendar_id_key, t.""task_id_key"" AS task_id_key,",
				                    "t.""driving_path_flag"" AS driving_path_flag, TRY_CAST(t.""remainingduration"" AS DOUBLE) AS remainingduration, TRY_CAST(SUBSTR(CAST(t.""early_end_date"" AS VARCHAR), 1, 10) AS DATE) AS early_end_date,",
				                    "TRY_CAST(SUBSTR(CAST(t.""monthupdate"" AS VARCHAR), 1, 10) AS DATE) AS monthupdate,",
				                    "t.""task_name"" AS task_name, TRY_CAST(SUBSTR(CAST(t.""data_date"" AS VARCHAR), 1, 10) AS DATE) AS data_date, TRY_CAST(SUBSTR(CAST(t.""act_end_date"" AS VARCHAR), 1, 10) AS DATE) AS act_end_date, TRY_CAST(SUBSTR(CAST(t.""finish"" AS VARCHAR), 1, 10) AS DATE) AS finish,",
				                    "t.""proj_id_key"" AS proj_id_key, t.""wbs_id_key"" AS wbs_id_key, TRY_CAST(t.""free_float"" AS DOUBLE) AS free_float, t.""cstr_type"" AS cstr_type,",
				                    "TRY_CAST(SUBSTR(CAST(t.""start"" AS VARCHAR), 1, 10) AS DATE) AS start, t.""filename"" AS filename, TRY_CAST(SUBSTR(CAST(t.""late_end_date"" AS VARCHAR), 1, 10) AS DATE) AS late_end_date,",
				                    "SPLIT_PART(SPLIT_PART(t.""filename"", '_', 1), '-', 1) AS project_code,",
				                    "SPLIT_PART(SPLIT_PART(t.""filename"", '_', 1), '-', 2) AS programme_type,",
				                    "SPLIT_PART(SPLIT_PART(t.""filename"", '_', 1), '-', 3) AS update_tag",
				                    "FROM prod_projectcontrols_p6.""01_xer_task"" t",
				                    "INNER JOIN kept_filenames kf ON t.""filename"" = kf.""filename""",
				                    "), task_update_parts AS (",
				                    "SELECT *,",
				                    "CASE WHEN update_tag IS NOT NULL AND REGEXP_LIKE(update_tag, '^BL') THEN TRUE ELSE FALSE END AS is_bl,",
				                    "TRY_CAST(NULLIF(REGEXP_EXTRACT(update_tag, '^([0-9]{2})', 1), '') AS INTEGER) AS tag_first_number,",
				                    "TRY_CAST(NULLIF(REGEXP_EXTRACT(update_tag, '([0-9]{2})$', 1), '') AS INTEGER) AS tag_last_number",
				                    "FROM task_raw",
				                    "), task_update_start AS (",
				                    "SELECT *,",
				                    "CASE WHEN tag_first_number IS NULL OR tag_last_number IS NULL THEN NULL WHEN tag_last_number > 12 THEN tag_last_number ELSE tag_first_number END AS update_year_number,",
				                    "CASE WHEN tag_first_number IS NULL OR tag_last_number IS NULL THEN NULL WHEN tag_last_number > 12 THEN tag_first_number ELSE tag_last_number END AS update_month_number",
				                    "FROM task_update_parts",
				                    "), task_with_update AS (",
				                    "SELECT *,",
				                    "CASE",
				                    "WHEN update_tag IS NULL OR update_tag = '' OR is_bl = TRUE THEN NULL",
				                    "WHEN update_month_number < 1 OR update_month_number > 12 OR update_year_number IS NULL THEN NULL",
				                    "ELSE CAST(date_add('day', -1, date_add('month', 1, date_trunc('month', TRY_CAST(CONCAT('20', LPAD(CAST(update_year_number AS VARCHAR), 2, '0'), '-', LPAD(CAST(update_month_number AS VARCHAR), 2, '0'), '-01') AS DATE)))) AS DATE)",
				                    "END AS parsed_update_date,",
				                    "CASE WHEN monthupdate IS NULL THEN NULL ELSE CAST(date_add('day', -1, date_add('month', 1, date_trunc('month', monthupdate))) AS DATE) END AS monthupdate_end_date",
				                    "FROM task_update_start",
				                    "), task_with_filled_update AS (",
				                    "SELECT *, COALESCE(parsed_update_date, monthupdate_end_date) AS update_date_filled",
				                    "FROM task_with_update",
				                    "), non_bl_dates AS (",
				                    "SELECT DISTINCT project_code, programme_type, update_date_filled AS update_date",
				                    "FROM task_with_filled_update",
				                    "WHERE is_bl = FALSE AND update_date_filled IS NOT NULL",
				                    "), update_candidates AS (",
				                    "SELECT u.task_row_id,",
				                    "CASE WHEN u.update_date_filled IS NULL THEN NULL ELSE CAST(date_add('day', -1, date_add('month', 1, date_trunc('month', date_add('month', (0 - shift_months), u.update_date_filled)))) AS DATE) END AS candidate_update_date,",
				                    "ROW_NUMBER() OVER (PARTITION BY u.task_row_id ORDER BY shift_months) AS candidate_rank",
				                    "FROM task_with_filled_update u",
				                    "CROSS JOIN UNNEST(SEQUENCE(0, CASE WHEN u.is_bl = TRUE AND u.update_date_filled IS NOT NULL THEN 240 ELSE 0 END)) AS s(shift_months)",
				                    "LEFT JOIN non_bl_dates nbd ON nbd.project_code = u.project_code AND nbd.programme_type = u.programme_type AND nbd.update_date = CASE WHEN u.update_date_filled IS NULL THEN NULL ELSE CAST(date_add('day', -1, date_add('month', 1, date_trunc('month', date_add('month', (0 - shift_months), u.update_date_filled)))) AS DATE) END",
				                    "WHERE u.is_bl = FALSE OR nbd.update_date IS NULL",
				                    "), task_base AS (",
				                    "SELECT u.status_code, u.task_code, u.total_float, u.task_type, u.id_name, u.early_start_date, u.calendar_id_key, u.task_id_key,",
				                    "u.driving_path_flag, u.remainingduration, u.early_end_date, u.monthupdate, u.task_name, u.data_date, u.act_end_date, u.finish,",
				                    "u.proj_id_key, u.wbs_id_key, u.free_float, u.cstr_type, u.start, u.filename, u.late_end_date, u.project_code, u.programme_type,",
				                    "c.candidate_update_date AS update_date,",
				                    "CASE WHEN u.status_code = 'Complete' THEN u.finish ELSE u.early_end_date END AS effective_early_end,",
				                    "CASE WHEN u.status_code = 'Complete' THEN u.finish ELSE u.late_end_date END AS effective_late_end",
				                    "FROM task_with_filled_update u",
				                    "LEFT JOIN update_candidates c ON c.task_row_id = u.task_row_id AND c.candidate_rank = 1",
				                    "), task_named AS (",
				                    "SELECT b.*,",
				                    "COALESCE(alt_project.""projectname"", orig_project.""projectname"") AS project_name,",
				                    "COALESCE(COALESCE(alt_project.""projectname"", orig_project.""projectname""), b.project_code) AS project_group_key",
				                    "FROM task_base b",
				                    "LEFT JOIN prod_projectcontrols_linkedsitereports.""dbo_project"" alt_project ON alt_project.""projectno"" = CASE WHEN b.project_code LIKE 'C%' THEN CONCAT('J', SUBSTR(b.project_code, 2)) ELSE b.project_code END",
				                    "LEFT JOIN prod_projectcontrols_linkedsitereports.""dbo_project"" orig_project ON orig_project.""projectno"" = b.project_code",
				                    "), task_snapshot AS (",
				                    "SELECT project_group_key, task_code, update_date,",
				                    "MAX(start) AS snapshot_start, MAX(finish) AS snapshot_finish, MAX(data_date) AS snapshot_data_date,",
				                    "MAX(remainingduration) AS snapshot_remainingduration, MAX(COALESCE(early_start_date, start)) AS snapshot_effective_start,",
				                    "MAX(COALESCE(early_end_date, finish)) AS snapshot_effective_finish,",
				                    "CASE WHEN COUNT(DISTINCT status_code) = 1 THEN MIN(status_code) ELSE NULL END AS snapshot_status",
				                    "FROM task_named",
				                    "GROUP BY project_group_key, task_code, update_date",
				                    "), task_snapshot_prev AS (",
				                    "SELECT project_group_key, task_code, update_date,",
				                    "LAG(update_date) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_update_date,",
				                    "LAG(snapshot_start) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_start,",
				                    "LAG(snapshot_finish) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_finish,",
				                    "LAG(snapshot_data_date) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_data_date,",
				                    "LAG(snapshot_remainingduration) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_remainingduration,",
				                    "LAG(snapshot_effective_start) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_effective_start,",
				                    "LAG(snapshot_effective_finish) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_effective_finish,",
				                    "LAG(snapshot_status) OVER (PARTITION BY project_group_key, task_code ORDER BY update_date) AS previous_task_status",
				                    "FROM task_snapshot",
				                    "), project_updates AS (",
				                    "SELECT DISTINCT project_group_key, update_date FROM task_named WHERE update_date IS NOT NULL",
				                    "), project_updates_prev AS (",
				                    "SELECT project_group_key, update_date, LAG(update_date) OVER (PARTITION BY project_group_key ORDER BY update_date) AS previous_project_update_date",
				                    "FROM project_updates",
				                    "), project_data_dates AS (",
				                    "SELECT DISTINCT project_group_key, data_date FROM task_named WHERE data_date IS NOT NULL",
				                    "), project_data_dates_prev AS (",
				                    "SELECT project_group_key, data_date, LAG(data_date) OVER (PARTITION BY project_group_key ORDER BY data_date) AS previous_data_date",
				                    "FROM project_data_dates",
				                    "), baseline_first_update AS (",
				                    "SELECT project_code, MIN(update_date) AS first_update_date FROM task_named GROUP BY project_code",
				                    "), baseline_lookup AS (",
				                    "SELECT n.project_code, n.task_code, MAX(n.start) AS baseline_start, MAX(n.finish) AS baseline_finish,",
				                    "MAX(n.effective_early_end) AS baseline_effective_early_end, MAX(n.effective_late_end) AS baseline_effective_late_end",
				                    "FROM task_named n",
				                    "INNER JOIN baseline_first_update b ON b.project_code = n.project_code AND b.first_update_date = n.update_date",
				                    "GROUP BY n.project_code, n.task_code",
				                    "), adjusted_first_month AS (",
				                    "SELECT project_code, task_code, MIN(monthupdate) AS first_added_month FROM task_named GROUP BY project_code, task_code",
				                    "), adjusted_lookup AS (",
				                    "SELECT n.project_code, n.task_code, f.first_added_month, MIN(n.start) AS adjusted_baseline_start, MAX(n.finish) AS adjusted_baseline_finish",
				                    "FROM task_named n",
				                    "INNER JOIN adjusted_first_month f ON f.project_code = n.project_code AND f.task_code = n.task_code AND f.first_added_month = n.monthupdate",
				                    "GROUP BY n.project_code, n.task_code, f.first_added_month",
				                    "), project_first_month AS (",
				                    "SELECT project_code, MIN(monthupdate) AS project_first_month FROM task_named GROUP BY project_code",
				                    "), task_joined AS (",
				                    "SELECT n.*, sp.previous_task_update_date, sp.previous_task_start, sp.previous_task_finish, sp.previous_task_data_date,",
				                    "sp.previous_task_remainingduration, sp.previous_task_effective_start, sp.previous_task_effective_finish, sp.previous_task_status,",
				                    "pu.previous_project_update_date, pps.snapshot_finish AS project_previous_task_finish, pps.snapshot_data_date AS project_previous_task_data_date,",
				                    "pps.snapshot_status AS project_previous_task_status, pdd.previous_data_date,",
				                    "bl.baseline_start, bl.baseline_finish, bl.baseline_effective_early_end, bl.baseline_effective_late_end,",
				                    "adj.adjusted_baseline_start, adj.adjusted_baseline_finish, adj.first_added_month, pfm.project_first_month",
				                    "FROM task_named n",
				                    "LEFT JOIN task_snapshot_prev sp ON sp.project_group_key = n.project_group_key AND sp.task_code = n.task_code AND sp.update_date = n.update_date",
				                    "LEFT JOIN project_updates_prev pu ON pu.project_group_key = n.project_group_key AND pu.update_date = n.update_date",
				                    "LEFT JOIN task_snapshot pps ON pps.project_group_key = n.project_group_key AND pps.task_code = n.task_code AND pps.update_date = pu.previous_project_update_date",
				                    "LEFT JOIN project_data_dates_prev pdd ON pdd.project_group_key = n.project_group_key AND pdd.data_date = n.data_date",
				                    "LEFT JOIN baseline_lookup bl ON bl.project_code = n.project_code AND bl.task_code = n.task_code",
				                    "LEFT JOIN adjusted_lookup adj ON adj.project_code = n.project_code AND adj.task_code = n.task_code",
				                    "LEFT JOIN project_first_month pfm ON pfm.project_code = n.project_code",
				                    "), network_inputs AS (",
				                    "SELECT *,",
				                    "CAST(previous_task_finish AS DATE) AS finish_var_start_date, CAST(finish AS DATE) AS finish_var_end_date,",
				                    "CAST(previous_task_start AS DATE) AS start_var_start_date, CAST(start AS DATE) AS start_var_end_date,",
				                    "CAST(baseline_finish AS DATE) AS baseline_var_start_date, CAST(finish AS DATE) AS baseline_var_end_date",
				                    "FROM task_joined",
				                    "), network_bounds AS (",
				                    "SELECT *,",
				                    "LEAST(finish_var_start_date, finish_var_end_date) AS finish_var_min_date, GREATEST(finish_var_start_date, finish_var_end_date) AS finish_var_max_date,",
				                    "LEAST(start_var_start_date, start_var_end_date) AS start_var_min_date, GREATEST(start_var_start_date, start_var_end_date) AS start_var_max_date,",
				                    "LEAST(baseline_var_start_date, baseline_var_end_date) AS baseline_var_min_date, GREATEST(baseline_var_start_date, baseline_var_end_date) AS baseline_var_max_date",
				                    "FROM network_inputs",
				                    "), network_parts AS (",
				                    "SELECT *,",
				                    "CASE WHEN finish_var_start_date IS NULL OR finish_var_end_date IS NULL THEN NULL ELSE date_diff('day', finish_var_min_date, finish_var_max_date) + 1 END AS finish_var_days,",
				                    "CASE WHEN start_var_start_date IS NULL OR start_var_end_date IS NULL THEN NULL ELSE date_diff('day', start_var_min_date, start_var_max_date) + 1 END AS start_var_days,",
				                    "CASE WHEN baseline_var_start_date IS NULL OR baseline_var_end_date IS NULL THEN NULL ELSE date_diff('day', baseline_var_min_date, baseline_var_max_date) + 1 END AS baseline_var_days",
				                    "FROM network_bounds",
				                    "), network_calcs AS (",
				                    "SELECT *,",
				                    "CAST(FLOOR(finish_var_days / 7.0) AS INTEGER) AS finish_var_full_weeks, CAST(MOD(finish_var_days, 7) AS INTEGER) AS finish_var_remainder, day_of_week(finish_var_min_date) AS finish_var_dow,",
				                    "CAST(FLOOR(start_var_days / 7.0) AS INTEGER) AS start_var_full_weeks, CAST(MOD(start_var_days, 7) AS INTEGER) AS start_var_remainder, day_of_week(start_var_min_date) AS start_var_dow,",
				                    "CAST(FLOOR(baseline_var_days / 7.0) AS INTEGER) AS baseline_var_full_weeks, CAST(MOD(baseline_var_days, 7) AS INTEGER) AS baseline_var_remainder, day_of_week(baseline_var_min_date) AS baseline_var_dow",
				                    "FROM network_parts",
				                    ")",
				                    "SELECT status_code, task_code, total_float, task_type, id_name, early_start_date, calendar_id_key, task_id_key, driving_path_flag, remainingduration,",
				                    "early_end_date, monthupdate, task_name, data_date, act_end_date, finish, proj_id_key, wbs_id_key, free_float, cstr_type, start, filename, late_end_date,",
				                    "project_code AS ""ProjectCode"", update_date AS ""UpdateDate"", project_name AS ""ProjectName"",",
				                    "CASE WHEN finish_var_start_date IS NULL OR finish_var_end_date IS NULL THEN 0 WHEN finish_var_start_date = finish_var_end_date THEN 0 ELSE (CASE WHEN finish_var_end_date >= finish_var_start_date THEN 1 ELSE -1 END) * (finish_var_full_weeks * 5 + GREATEST(0, LEAST(finish_var_remainder, 6 - finish_var_dow)) + GREATEST(0, finish_var_remainder - (8 - finish_var_dow))) END AS ""Finish_Variance_Previous_Month"",",
				                    "CASE WHEN NOT (task_type IN ('TT_Task', 'TT_Rsrc', 'TT_Mile', 'TT_FinMile') AND task_code IS NOT NULL AND project_name IS NOT NULL AND COALESCE(status_code, '') <> 'Complete' AND data_date IS NOT NULL AND update_date IS NOT NULL) THEN 'Not Driven' WHEN status_code = 'Not Started' AND previous_task_update_date IS NOT NULL AND previous_task_data_date IS NOT NULL AND previous_task_status = 'Not Started' AND date_diff('day', CAST(previous_task_data_date AS DATE), CAST(data_date AS DATE)) > 0 AND date_diff('day', CAST(previous_task_effective_start AS DATE), CAST(COALESCE(early_start_date, start) AS DATE)) > 0 AND ABS(date_diff('day', CAST(previous_task_effective_start AS DATE), CAST(COALESCE(early_start_date, start) AS DATE)) - date_diff('day', CAST(previous_task_data_date AS DATE), CAST(data_date AS DATE))) <= 1 AND COALESCE(early_start_date, start) IS NOT NULL AND COALESCE(early_end_date, finish) IS NOT NULL AND previous_task_effective_start IS NOT NULL AND previous_task_effective_finish IS NOT NULL AND ABS(date_diff('day', CAST(COALESCE(early_start_date, start) AS DATE), CAST(COALESCE(early_end_date, finish) AS DATE)) - date_diff('day', CAST(previous_task_effective_start AS DATE), CAST(previous_task_effective_finish AS DATE))) <= 1 THEN 'Not Started - Slippage Matches Update Period' WHEN status_code = 'In Progress' AND previous_task_update_date IS NOT NULL AND previous_task_data_date IS NOT NULL AND previous_task_status = 'In Progress' AND date_diff('day', CAST(previous_task_data_date AS DATE), CAST(data_date AS DATE)) > 0 AND remainingduration IS NOT NULL AND previous_task_remainingduration IS NOT NULL AND remainingduration >= previous_task_remainingduration - 1 AND date_diff('day', CAST(previous_task_effective_finish AS DATE), CAST(COALESCE(early_end_date, finish) AS DATE)) > 0 AND ABS(date_diff('day', CAST(previous_task_effective_finish AS DATE), CAST(COALESCE(early_end_date, finish) AS DATE)) - date_diff('day', CAST(previous_task_data_date AS DATE), CAST(data_date AS DATE))) <= 1 THEN 'In Progress - Stagnating Progress' WHEN status_code = 'Not Started' AND COALESCE(early_start_date, start) IS NOT NULL AND CAST(COALESCE(early_start_date, start) AS DATE) = CAST(data_date AS DATE) THEN 'Not Started - Early Start Sitting on Data Date' WHEN status_code = 'In Progress' AND early_start_date IS NOT NULL AND remainingduration IS NOT NULL AND remainingduration > 0 AND CAST(COALESCE(early_start_date, start) AS DATE) = CAST(data_date AS DATE) THEN 'In Progress - Remaining Work Sitting on Data Date' ELSE 'Not Driven' END AS ""Driven_DataDate"",",
				                    "CASE WHEN baseline_var_start_date IS NULL OR baseline_var_end_date IS NULL THEN NULL WHEN baseline_var_start_date = baseline_var_end_date THEN 0 ELSE (CASE WHEN baseline_var_end_date >= baseline_var_start_date THEN 1 ELSE -1 END) * (baseline_var_full_weeks * 5 + GREATEST(0, LEAST(baseline_var_remainder, 6 - baseline_var_dow)) + GREATEST(0, baseline_var_remainder - (8 - baseline_var_dow))) END AS ""Variance_Finish_BL"",",
				                    "baseline_finish AS ""Baseline Finish"", baseline_start AS ""Baseline Start"", COALESCE(previous_task_start, start) AS ""Previous Month Start"", COALESCE(previous_task_finish, finish) AS ""Previous Month Finish"",",
				                    "CASE WHEN previous_project_update_date IS NOT NULL AND project_previous_task_finish > project_previous_task_data_date AND project_previous_task_finish <= data_date AND COALESCE(status_code, '') <> 'Complete' THEN 1 ELSE 0 END AS ""Planned Not Completed Last Period"",",
				                    "CASE WHEN start_var_start_date IS NULL OR start_var_end_date IS NULL THEN 0 WHEN start_var_start_date = start_var_end_date THEN 0 ELSE (CASE WHEN start_var_end_date >= start_var_start_date THEN 1 ELSE -1 END) * (start_var_full_weeks * 5 + GREATEST(0, LEAST(start_var_remainder, 6 - start_var_dow)) + GREATEST(0, start_var_remainder - (8 - start_var_dow))) END AS ""Start_Variance_Previous_Month"",",
				                    "previous_data_date AS ""PreviousDataDate"", previous_task_remainingduration AS ""Previous Remaining Working Days"",",
				                    "CASE WHEN previous_project_update_date IS NOT NULL AND project_previous_task_finish > project_previous_task_data_date AND project_previous_task_finish <= data_date THEN 1 ELSE 0 END AS ""Planned Last Period"",",
				                    "CASE WHEN status_code = 'Complete' AND project_previous_task_status <> 'Complete' AND project_previous_task_status IS NOT NULL THEN 1 ELSE 0 END AS ""Completed Last Period"",",
				                    "CASE WHEN previous_project_update_date IS NOT NULL AND project_previous_task_finish > project_previous_task_data_date AND project_previous_task_finish <= data_date AND status_code = 'Complete' THEN 1 ELSE 0 END AS ""Completed of Planned Last Period"",",
				                    "baseline_effective_early_end AS ""Baseline Effective_Early_End"", baseline_effective_late_end AS ""Baseline Effective_Late_End"",",
				                    "adjusted_baseline_finish AS ""Adjusted Baseline Finish"", adjusted_baseline_start AS ""Adjusted Baseline Start"", first_added_month AS ""Adjusted Baseline Source Month"",",
				                    "CASE WHEN first_added_month IS NULL THEN NULL WHEN project_first_month IS NULL THEN 'Unknown' WHEN first_added_month = project_first_month THEN 'Original Baseline' WHEN first_added_month > project_first_month THEN 'Later Update' ELSE 'Unknown' END AS ""Adjusted Baseline Source""",
				                    "FROM network_calcs"
				                },
				                " "
				            ),
				            null
				        ),
				
				    Typed =
				        Table.TransformColumnTypes(
				            SourceRaw,
				            {
				                {"act_end_date", type datetime},
				                {"UpdateDate", type date},
				                {"early_start_date", type datetime},
				                {"early_end_date", type datetime},
				                {"late_end_date", type datetime},
				                {"start", type datetime},
				                {"finish", type datetime},
				                {"data_date", type datetime},
				                {"monthupdate", type date},
				                {"total_float", type number},
				                {"free_float", type number},
				                {"remainingduration", type number},
				                {"Finish_Variance_Previous_Month", Int64.Type},
				                {"Variance_Finish_BL", Int64.Type},
				                {"Baseline Finish", type datetime},
				                {"Baseline Start", type datetime},
				                {"Previous Month Start", type datetime},
				                {"Previous Month Finish", type datetime},
				                {"Planned Not Completed Last Period", Int64.Type},
				                {"Start_Variance_Previous_Month", Int64.Type},
				                {"PreviousDataDate", type datetime},
				                {"Previous Remaining Working Days", type number},
				                {"Planned Last Period", Int64.Type},
				                {"Completed Last Period", Int64.Type},
				                {"Completed of Planned Last Period", Int64.Type},
				                {"Baseline Effective_Early_End", type datetime},
				                {"Baseline Effective_Late_End", type datetime},
				                {"Adjusted Baseline Finish", type datetime},
				                {"Adjusted Baseline Start", type datetime},
				                {"Adjusted Baseline Source Month", type datetime}
				            }
				        ),
				
				    Renamed =
				        Table.RenameColumns(
				            Typed,
				            {
				                {"start", "Start"},
				                {"finish", "Finish"},
				                {"remainingduration", "remaining_duration"}
				            }
				        ),
				
				    Final =
				        Table.SelectColumns(Renamed,{"status_code", "task_code", "total_float", "task_type", "id_name", "early_start_date", "calendar_id_key", "task_id_key", "driving_path_flag", "remaining_duration", "early_end_date", "monthupdate", "task_name", "data_date", "act_end_date", "Finish", "proj_id_key", "wbs_id_key", "free_float", "cstr_type", "Start", "filename", "late_end_date", "ProjectCode", "UpdateDate", "ProjectName", "Finish_Variance_Previous_Month", "Driven_DataDate", "Variance_Finish_BL", "Baseline Finish", "Baseline Start", "Previous Month Start", "Previous Month Finish", "Planned Not Completed Last Period", "Start_Variance_Previous_Month", "PreviousDataDate", "Previous Remaining Working Days", "Planned Last Period", "Completed Last Period", "Completed of Planned Last Period", "Baseline Effective_Early_End", "Baseline Effective_Late_End", "Adjusted Baseline Finish", "Adjusted Baseline Start", "Adjusted Baseline Source Month", "Adjusted Baseline Source"})
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

