table '02 XER_PROJECT'
	lineageTag: 4174ebbd-f58e-48fd-9c0f-aa9cf47af1ac

	column last_recalc_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1dae6a1-f1b0-48e3-bef0-4ff9cbc40a73
		summarizeBy: none
		sourceColumn: last_recalc_date

		variation Variation
			isDefault
			relationship: 8bb9386b-77c5-41d2-a683-344e95b77933
			defaultHierarchy: LocalDateTable_ae67810d-93ce-4197-a74e-3bb20d9bed60.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_short_name
		dataType: string
		lineageTag: bbc295b0-09b3-43cb-8d81-e8a50635b646
		summarizeBy: none
		sourceColumn: proj_short_name

		annotation SummarizationSetBy = Automatic

	column proj_id_key
		dataType: string
		lineageTag: 43bfde4d-82c8-4b06-a306-35d6426f5eb4
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	column proj_id
		dataType: string
		lineageTag: 1425102b-cebb-4d9b-aded-9236d0d2032d
		summarizeBy: none
		sourceColumn: proj_id

		annotation SummarizationSetBy = Automatic

	column server
		dataType: string
		lineageTag: 01764705-a26f-457f-8484-ccc486c6f4fd
		summarizeBy: none
		sourceColumn: server

		annotation SummarizationSetBy = Automatic

	column database
		dataType: string
		lineageTag: d8f03402-3ff8-4c44-b572-9393d708546b
		summarizeBy: none
		sourceColumn: database

		annotation SummarizationSetBy = Automatic

	column fy_start_month_num
		dataType: string
		lineageTag: 20693bc4-216f-4502-a2ae-93c6a19fe731
		summarizeBy: none
		sourceColumn: fy_start_month_num

		annotation SummarizationSetBy = Automatic

	column rsrc_self_add_flag
		dataType: string
		lineageTag: aab2d0d0-dbb7-4960-8c7b-64a32ec6715c
		summarizeBy: none
		sourceColumn: rsrc_self_add_flag

		annotation SummarizationSetBy = Automatic

	column allow_complete_flag
		dataType: string
		lineageTag: 2e1277c5-4f2a-4545-b937-f794a629670f
		summarizeBy: none
		sourceColumn: allow_complete_flag

		annotation SummarizationSetBy = Automatic

	column rsrc_multi_assign_flag
		dataType: string
		lineageTag: cf6a2a6f-9999-44c3-a1b7-a7f93619e44e
		summarizeBy: none
		sourceColumn: rsrc_multi_assign_flag

		annotation SummarizationSetBy = Automatic

	column checkout_flag
		dataType: string
		lineageTag: 29457af2-a215-483c-9756-abb7a007d3ab
		summarizeBy: none
		sourceColumn: checkout_flag

		annotation SummarizationSetBy = Automatic

	column project_flag
		dataType: string
		lineageTag: aa4863b9-2007-4aec-851e-14203c6208f6
		summarizeBy: none
		sourceColumn: project_flag

		annotation SummarizationSetBy = Automatic

	column step_complete_flag
		dataType: string
		lineageTag: 8a904f3f-b916-4195-9f24-987fff41fbbb
		summarizeBy: none
		sourceColumn: step_complete_flag

		annotation SummarizationSetBy = Automatic

	column cost_qty_recalc_flag
		dataType: string
		lineageTag: dff560b5-5553-48c1-90b1-934e157ffddb
		summarizeBy: none
		sourceColumn: cost_qty_recalc_flag

		annotation SummarizationSetBy = Automatic

	column batch_sum_flag
		dataType: string
		lineageTag: bea6317b-624a-4781-a51a-5839d2ea4d7b
		summarizeBy: none
		sourceColumn: batch_sum_flag

		annotation SummarizationSetBy = Automatic

	column name_sep_char
		dataType: string
		lineageTag: 74bd8643-b155-4c32-aadf-b29045101a0c
		summarizeBy: none
		sourceColumn: name_sep_char

		annotation SummarizationSetBy = Automatic

	column def_complete_pct_type
		dataType: string
		lineageTag: e680242e-277b-4bf9-a060-72149bc4d878
		summarizeBy: none
		sourceColumn: def_complete_pct_type

		annotation SummarizationSetBy = Automatic

	column acct_id
		dataType: string
		lineageTag: b18277dd-7e32-475b-b906-f78af02570f9
		summarizeBy: none
		sourceColumn: acct_id

		annotation SummarizationSetBy = Automatic

	column orig_proj_id
		dataType: string
		lineageTag: 07897801-e18b-4e4c-a3bb-eff643169403
		summarizeBy: none
		sourceColumn: orig_proj_id

		annotation SummarizationSetBy = Automatic

	column source_proj_id
		dataType: string
		lineageTag: 552c0560-0af1-4ddb-8059-afb4e72ef14d
		summarizeBy: none
		sourceColumn: source_proj_id

		annotation SummarizationSetBy = Automatic

	column base_type_id
		dataType: string
		lineageTag: b9666703-6812-49dd-bc05-86fbaa8a1cc0
		summarizeBy: none
		sourceColumn: base_type_id

		annotation SummarizationSetBy = Automatic

	column clndr_id
		dataType: string
		lineageTag: 133e4de9-fe79-41b8-ad1e-ab27edc55fa0
		summarizeBy: none
		sourceColumn: clndr_id

		annotation SummarizationSetBy = Automatic

	column sum_base_proj_id
		dataType: string
		lineageTag: 23f72cf8-1317-4764-a5b3-a6ca1ae0d36e
		summarizeBy: none
		sourceColumn: sum_base_proj_id

		annotation SummarizationSetBy = Automatic

	column task_code_base
		dataType: string
		lineageTag: 0691eacd-a3bb-4855-b02e-1d77f3796dff
		summarizeBy: none
		sourceColumn: task_code_base

		annotation SummarizationSetBy = Automatic

	column task_code_step
		dataType: string
		lineageTag: 960d65f3-e82e-4052-8514-15111e960652
		summarizeBy: none
		sourceColumn: task_code_step

		annotation SummarizationSetBy = Automatic

	column priority_num
		dataType: string
		lineageTag: c702d612-c854-43ca-bcdc-45bf4f436270
		summarizeBy: none
		sourceColumn: priority_num

		annotation SummarizationSetBy = Automatic

	column wbs_max_sum_level
		dataType: string
		lineageTag: 6af2518a-6399-4241-8270-8810a95ba6ef
		summarizeBy: none
		sourceColumn: wbs_max_sum_level

		annotation SummarizationSetBy = Automatic

	column strgy_priority_num
		dataType: string
		lineageTag: db7bb8a8-6883-4fac-8cf5-e05c028f5643
		summarizeBy: none
		sourceColumn: strgy_priority_num

		annotation SummarizationSetBy = Automatic

	column last_checksum
		dataType: string
		lineageTag: 29d67f24-8a5b-44fa-ba83-cfff40fb5543
		summarizeBy: none
		sourceColumn: last_checksum

		annotation SummarizationSetBy = Automatic

	column critical_drtn_hr_cnt
		dataType: string
		lineageTag: e49d677c-0912-421d-ab94-c94a1bc55f48
		summarizeBy: none
		sourceColumn: critical_drtn_hr_cnt

		annotation SummarizationSetBy = Automatic

	column def_cost_per_qty
		dataType: string
		lineageTag: ef93ecf0-cc45-4148-8a13-43aead4e80e3
		summarizeBy: none
		sourceColumn: def_cost_per_qty

		annotation SummarizationSetBy = Automatic

	column plan_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dc6f0acf-cf85-4f89-9a8e-8ad67afa69bd
		summarizeBy: none
		sourceColumn: plan_start_date

		variation Variation
			isDefault
			relationship: 99b9ad66-0068-43a4-8c80-c2217e75a527
			defaultHierarchy: LocalDateTable_84b136d4-0c16-430a-b2a8-6b6e79f3cbc1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column plan_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c43a3e73-9db0-49f0-bad3-674230e2b674
		summarizeBy: none
		sourceColumn: plan_end_date

		variation Variation
			isDefault
			relationship: c0cf0c74-4a51-4198-8885-0f0d810fb174
			defaultHierarchy: LocalDateTable_bfd2190b-c248-4ffa-ac5c-c17cb1978ba9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column scd_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4b5014c4-a143-4dc7-84a6-b066e744d22a
		summarizeBy: none
		sourceColumn: scd_end_date

		variation Variation
			isDefault
			relationship: af828b89-f188-4776-b6f3-8de83a023bf0
			defaultHierarchy: LocalDateTable_18c5c2b4-20fd-4cfb-a98d-bfcdfff2b369.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column add_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e47c7450-8045-4f2e-8dde-f1ff3906e15c
		summarizeBy: none
		sourceColumn: add_date

		variation Variation
			isDefault
			relationship: 34918c33-091b-45d5-899d-8496fc090881
			defaultHierarchy: LocalDateTable_359244bb-a97a-4f99-85c1-e0cf0f71bdc7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_tasksum_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5554d99a-dad3-487d-a49c-ca65f88a755d
		summarizeBy: none
		sourceColumn: last_tasksum_date

		variation Variation
			isDefault
			relationship: f13bc119-5983-478b-a1e7-a499ad8334e7
			defaultHierarchy: LocalDateTable_7190bfff-72ca-4039-82ae-864bae8e5acf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fcst_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b31760b-6b7d-4651-9fe3-33f4db3b5f15
		summarizeBy: none
		sourceColumn: fcst_start_date

		variation Variation
			isDefault
			relationship: 0bfd1021-8285-4f34-9441-d50613763ca4
			defaultHierarchy: LocalDateTable_cfb244e8-624b-4c14-ba72-18e4b4423952.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column def_duration_type
		dataType: string
		lineageTag: 4ad5b30b-a483-4582-b9b5-72c645da10d5
		summarizeBy: none
		sourceColumn: def_duration_type

		annotation SummarizationSetBy = Automatic

	column task_code_prefix
		dataType: string
		lineageTag: 44db55f8-ab19-413b-bf1a-d388785ec104
		summarizeBy: none
		sourceColumn: task_code_prefix

		annotation SummarizationSetBy = Automatic

	column guid
		dataType: string
		lineageTag: 073f66bb-9d77-462d-949f-50f23c7be6fa
		summarizeBy: none
		sourceColumn: guid

		annotation SummarizationSetBy = Automatic

	column def_qty_type
		dataType: string
		lineageTag: 7d54557c-21d3-40bd-aaf3-32f3570ff726
		summarizeBy: none
		sourceColumn: def_qty_type

		annotation SummarizationSetBy = Automatic

	column add_by_name
		dataType: string
		lineageTag: 5b230758-339b-4815-9409-f4de1b312ca8
		summarizeBy: none
		sourceColumn: add_by_name

		annotation SummarizationSetBy = Automatic

	column web_local_root_path
		dataType: string
		lineageTag: 1952b3e0-201c-4906-8c87-2c8daf472e91
		summarizeBy: none
		sourceColumn: web_local_root_path

		annotation SummarizationSetBy = Automatic

	column proj_url
		dataType: string
		lineageTag: 6809f025-3dfb-4cc0-b6f9-6fb79c395d38
		summarizeBy: none
		sourceColumn: proj_url

		annotation SummarizationSetBy = Automatic

	column def_rate_type
		dataType: string
		lineageTag: 66025a1c-a454-4101-a9ae-03a9066e6346
		summarizeBy: none
		sourceColumn: def_rate_type

		annotation SummarizationSetBy = Automatic

	column add_act_remain_flag
		dataType: string
		lineageTag: bb9971e7-35ec-49a3-b48a-4842a56f3dc3
		summarizeBy: none
		sourceColumn: add_act_remain_flag

		annotation SummarizationSetBy = Automatic

	column act_this_per_link_flag
		dataType: string
		lineageTag: ec93928e-6a20-46a3-a201-c56c10b283b5
		summarizeBy: none
		sourceColumn: act_this_per_link_flag

		annotation SummarizationSetBy = Automatic

	column def_task_type
		dataType: string
		lineageTag: 6506d5c6-9087-48be-b5c4-972fe29dae90
		summarizeBy: none
		sourceColumn: def_task_type

		annotation SummarizationSetBy = Automatic

	column act_pct_link_flag
		dataType: string
		lineageTag: 3c0c95d1-1189-4f9d-bfd9-c7492e830ac3
		summarizeBy: none
		sourceColumn: act_pct_link_flag

		annotation SummarizationSetBy = Automatic

	column critical_path_type
		dataType: string
		lineageTag: 04f61ad0-42d8-4e98-b511-444533fcd3be
		summarizeBy: none
		sourceColumn: critical_path_type

		annotation SummarizationSetBy = Automatic

	column task_code_prefix_flag
		dataType: string
		lineageTag: 8145b1f8-a87d-4810-b213-b4de8eab1dde
		summarizeBy: none
		sourceColumn: task_code_prefix_flag

		annotation SummarizationSetBy = Automatic

	column def_rollup_dates_flag
		dataType: string
		lineageTag: cd75617c-63a5-40bc-bc2b-d2ceedc2545e
		summarizeBy: none
		sourceColumn: def_rollup_dates_flag

		annotation SummarizationSetBy = Automatic

	column use_project_baseline_flag
		dataType: string
		lineageTag: 0e9d0ea7-9898-422a-8c84-765ef66b5af3
		summarizeBy: none
		sourceColumn: use_project_baseline_flag

		annotation SummarizationSetBy = Automatic

	column rem_target_link_flag
		dataType: string
		lineageTag: b9d362b2-4c26-46fd-8bf2-98a5a750dafc
		summarizeBy: none
		sourceColumn: rem_target_link_flag

		annotation SummarizationSetBy = Automatic

	column reset_planned_flag
		dataType: string
		lineageTag: 00322f39-4692-4d7a-aad6-d453cdbdd94d
		summarizeBy: none
		sourceColumn: reset_planned_flag

		annotation SummarizationSetBy = Automatic

	column allow_neg_act_flag
		dataType: string
		lineageTag: 4405890f-a495-44f2-b8da-d89626ee4fc7
		summarizeBy: none
		sourceColumn: allow_neg_act_flag

		annotation SummarizationSetBy = Automatic

	column sum_assign_level
		dataType: string
		lineageTag: 2f63fca3-0b47-441a-8935-4c7678c787bf
		summarizeBy: none
		sourceColumn: sum_assign_level

		annotation SummarizationSetBy = Automatic

	column last_fin_dates_id
		dataType: string
		lineageTag: 18d5bd64-9097-40d6-8a9b-f5e41c2cec00
		summarizeBy: none
		sourceColumn: last_fin_dates_id

		annotation SummarizationSetBy = Automatic

	column last_baseline_update_date
		dataType: string
		lineageTag: 2fe20cdb-c9c2-4d6e-b1f3-1330bf26b2a2
		summarizeBy: none
		sourceColumn: last_baseline_update_date

		annotation SummarizationSetBy = Automatic

	column cr_external_key
		dataType: string
		lineageTag: 5375dc12-aae5-4fbe-8936-15e4f425c3c8
		summarizeBy: none
		sourceColumn: cr_external_key

		annotation SummarizationSetBy = Automatic

	column apply_actuals_date
		dataType: string
		lineageTag: ead8e1e6-3258-4a13-8a40-fb0066052bd9
		summarizeBy: none
		sourceColumn: apply_actuals_date

		annotation SummarizationSetBy = Automatic

	column fintmpl_id
		dataType: string
		lineageTag: f1ee1265-1706-43ca-bf5c-29dc7e9f4dad
		summarizeBy: none
		sourceColumn: fintmpl_id

		annotation SummarizationSetBy = Automatic

	column last_schedule_date
		dataType: string
		lineageTag: 9b3913b4-643a-4f04-900b-ca35f6dc8164
		summarizeBy: none
		sourceColumn: last_schedule_date

		annotation SummarizationSetBy = Automatic

	column location_id
		dataType: string
		lineageTag: dbaea92a-4064-4425-8b79-d1a52b887c9c
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column loaded_scope_level
		dataType: string
		lineageTag: 499ffb4b-d518-4202-834d-43ef6d7fc713
		summarizeBy: none
		sourceColumn: loaded_scope_level

		annotation SummarizationSetBy = Automatic

	column export_flag
		dataType: string
		lineageTag: ce1d4c92-e30e-468c-91f4-d9e540176df0
		summarizeBy: none
		sourceColumn: export_flag

		annotation SummarizationSetBy = Automatic

	column new_fin_dates_id
		dataType: string
		lineageTag: b68c1ce1-e025-4dce-bd74-1f5dc585a910
		summarizeBy: none
		sourceColumn: new_fin_dates_id

		annotation SummarizationSetBy = Automatic

	column baselines_to_export
		dataType: string
		lineageTag: 14bd4393-2abf-452b-b807-51f3e22e04b8
		summarizeBy: none
		sourceColumn: baselines_to_export

		annotation SummarizationSetBy = Automatic

	column baseline_names_to_export
		dataType: string
		lineageTag: 3163e9e2-2273-42b7-ba3e-1680eafd4a1e
		summarizeBy: none
		sourceColumn: baseline_names_to_export

		annotation SummarizationSetBy = Automatic

	column next_data_date
		dataType: string
		lineageTag: c6415fbe-294f-4ed1-b5aa-82921851bfe4
		summarizeBy: none
		sourceColumn: next_data_date

		annotation SummarizationSetBy = Automatic

	column close_period_flag
		dataType: string
		lineageTag: c1321187-de97-406e-b735-7f12fe77dd94
		summarizeBy: none
		sourceColumn: close_period_flag

		annotation SummarizationSetBy = Automatic

	column sum_refresh_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69a7f1b8-06a2-496f-b753-bd3ded04d5ad
		summarizeBy: none
		sourceColumn: sum_refresh_date

		variation Variation
			isDefault
			relationship: c020e527-9ce6-4b43-ad97-08a94ac12648
			defaultHierarchy: LocalDateTable_2c36690b-0598-4562-be50-1776db5f0b56.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column trsrcsum_loaded
		dataType: string
		lineageTag: b055ce4b-878a-4907-b417-6476bd05dcc4
		summarizeBy: none
		sourceColumn: trsrcsum_loaded

		annotation SummarizationSetBy = Automatic

	column sumtask_loaded
		dataType: string
		lineageTag: 6d59de22-4610-4ec9-aff5-d04dfe245329
		summarizeBy: none
		sourceColumn: sumtask_loaded

		annotation SummarizationSetBy = Automatic

	column project
		dataType: string
		lineageTag: 4ec62923-4655-4365-b408-9680b8ffb7c6
		summarizeBy: none
		sourceColumn: project

		annotation SummarizationSetBy = Automatic

	column wbs_path
		dataType: string
		lineageTag: e4701dc4-4a45-4357-b75f-3ddc33ca6b86
		summarizeBy: none
		sourceColumn: wbs_path

		annotation SummarizationSetBy = Automatic

	column udf_datalake_status_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c83a5fc0-87d8-414b-bf17-b1484227245c
		summarizeBy: none
		sourceColumn: udf_datalake_status_date

		variation Variation
			isDefault
			relationship: 5f5df819-7c59-4aff-961d-bc2c79c0515a
			defaultHierarchy: LocalDateTable_a3ba81c9-ca15-4a52-8f32-4ff2153758ba.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column filename
		dataType: string
		lineageTag: 63f8515a-267c-4e91-9ba7-6b982a72085a
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6346e1e-af74-49db-ba13-ee228e7f491e
		summarizeBy: none
		sourceColumn: refresh_date

		variation Variation
			isDefault
			relationship: e5fc6112-5cc5-45e9-897f-40d0f981440f
			defaultHierarchy: LocalDateTable_76ea9526-88a5-43bf-9607-b2fbf158cc71.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition '02 XER_PROJECT' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("02_xer_project"),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"last_recalc_date", type datetime}, {"plan_start_date", type datetime}, {"scd_end_date", type datetime}, {"plan_end_date", type datetime}, {"add_date", type datetime}, {"last_tasksum_date", type datetime}, {"fcst_start_date", type datetime}, {"refresh_date", type datetime}, {"udf_datalake_status_date", type datetime}, {"sum_refresh_date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"last_recalc_date", type date}, {"plan_start_date", type date}, {"scd_end_date", type date}, {"plan_end_date", type date}, {"add_date", type date}, {"last_tasksum_date", type date}, {"fcst_start_date", type date}, {"refresh_date", type date}, {"udf_datalake_status_date", type date}, {"sum_refresh_date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

