table '02 XER_PROJECT'
	lineageTag: 4174ebbd-f58e-48fd-9c0f-aa9cf47af1ac

	column last_recalc_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1dae6a1-f1b0-48e3-bef0-4ff9cbc40a73
		summarizeBy: none
		sourceColumn: last_recalc_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_id_key
		dataType: string
		lineageTag: 43bfde4d-82c8-4b06-a306-35d6426f5eb4
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	column monthupdate
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 22d4b0fe-826a-4aa7-8d96-bf8d55a6f7f0
		summarizeBy: none
		sourceColumn: monthupdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ProjectCode
		dataType: string
		lineageTag: 0f593dc1-088a-4d29-89c5-f2d12ec0c6e3
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	partition '02 XER_PROJECT' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source =
				        fnAthenaSource(
				            "02_xer_project",
				            Text.Combine(
				                {
				                    "t.""last_recalc_date""",
				                    "t.""monthupdate""",
				                    "t.""proj_id_key""",
				                    "TRIM(UPPER(SPLIT_PART(t.""filename"", '-', 1))) AS ""ProjectCode"""
				                },
				                ", "
				            )
				        ),
				
				    ChangedTypes =
				        Table.TransformColumns(
				            Source,
				            {
				                {
				                    "last_recalc_date",
				                    each try Date.From(DateTime.FromText(Text.From(_))) otherwise try Date.From(_) otherwise null,
				                    type nullable date
				                },
				                {
				                    "monthupdate",
				                    each try Date.From(DateTime.FromText(Text.From(_))) otherwise try Date.From(_) otherwise null,
				                    type nullable date
				                }
				            }
				        ),
				
				    CleanProjectCode =
				        Table.TransformColumns(
				            ChangedTypes,
				            {
				                {
				                    "ProjectCode",
				                    each if _ = null then null else Text.Upper(Text.Trim(Text.Clean(Text.From(_)))),
				                    type nullable text
				                }
				            }
				        )
				in
				    CleanProjectCode

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

