table '02 XER_PROJECT'
	lineageTag: 4174ebbd-f58e-48fd-9c0f-aa9cf47af1ac

	column last_recalc_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1dae6a1-f1b0-48e3-bef0-4ff9cbc40a73
		summarizeBy: none
		sourceColumn: last_recalc_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_id_key
		dataType: string
		lineageTag: 43bfde4d-82c8-4b06-a306-35d6426f5eb4
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	partition '02 XER_PROJECT' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("02_xer_project", "t.""last_recalc_date"", t.""proj_id_key"""),
				
				    ChangedTypes =
				        Table.TransformColumns(
				            Source,
				            {
				                {
				                    "last_recalc_date",
				                    each try Date.From(DateTime.FromText(Text.From(_))) otherwise null,
				                    type nullable date
				                }
				            }
				        )
				in
				    ChangedTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

