table '02 XER_PROJECT'
	lineageTag: 4174ebbd-f58e-48fd-9c0f-aa9cf47af1ac

	column last_recalc_date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: f1dae6a1-f1b0-48e3-bef0-4ff9cbc40a73
		summarizeBy: none
		sourceColumn: last_recalc_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_short_name
		dataType: string
		lineageTag: bbc295b0-09b3-43cb-8d81-e8a50635b646
		summarizeBy: none
		sourceColumn: proj_short_name

		annotation SummarizationSetBy = Automatic

	column proj_id_key
		dataType: string
		lineageTag: 43bfde4d-82c8-4b06-a306-35d6426f5eb4
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: 63f8515a-267c-4e91-9ba7-6b982a72085a
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	partition '02 XER_PROJECT' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("02_xer_project"),
				
				    SelectedColumns =
				        Table.SelectColumns(
				            Source,
				            {
				                "proj_short_name",
				                "last_recalc_date",
				                "proj_id_key",
				                "filename"
				            }
				        ),
				
				    ChangedTypes =
				        Table.TransformColumns(
				            SelectedColumns,
				            {
				                {
				                    "last_recalc_date",
				                    each try Date.From(DateTime.FromText(Text.From(_))) otherwise null,
				                    type nullable date
				                }
				            }
				        )
				in
				    ChangedTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

