table '03 XER_PROJWBS'
	lineageTag: d38fbb96-999a-4ae4-9881-0c33936be526

	column wbs_name
		dataType: string
		lineageTag: 38e23525-b155-4a01-82e1-b3c9e639a3e2
		summarizeBy: none
		sourceColumn: wbs_name

		annotation SummarizationSetBy = Automatic

	column Path = PATH ('03 XER_PROJWBS'[wbs_id_key],'03 XER_PROJWBS'[parent_wbs_id_key])
		lineageTag: c68d4b25-9ae6-4e49-95fd-33c8709f83f4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level_1 = '03 XER_PROJWBS'[ProjectCode]
		lineageTag: 20447cf6-1c34-4bde-999c-ac027f78a9b7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level_2 =
			
			VAR WBS4_Name = LOOKUPVALUE(
			    '03 XER_PROJWBS'[wbs_name],
			    '03 XER_PROJWBS'[wbs_id_key],
			    PATHITEM('03 XER_PROJWBS'[Path], 2)
			)
			RETURN
			    COALESCE(WBS4_Name, '03 XER_PROJWBS'[Level_1])
		lineageTag: f4aea9f6-5d2c-4eee-bdb9-f44e82ec3031
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level_3 =
			
			VAR WBS4_Name = LOOKUPVALUE(
			    '03 XER_PROJWBS'[wbs_name],
			    '03 XER_PROJWBS'[wbs_id_key],
			    PATHITEM('03 XER_PROJWBS'[Path], 3)
			)
			RETURN
			    COALESCE(WBS4_Name, '03 XER_PROJWBS'[Level_2])
		lineageTag: e4071601-3d94-4cf3-98cf-828ad1e0b751
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level_4 = ```
			
			VAR WBS4_Name = LOOKUPVALUE(
			    '03 XER_PROJWBS'[wbs_name],
			    '03 XER_PROJWBS'[wbs_id_key],
			    PATHITEM('03 XER_PROJWBS'[Path], 4)
			)
			RETURN
			    COALESCE(WBS4_Name, '03 XER_PROJWBS'[Level_3])
			
			```
		lineageTag: cebb8249-83df-4e93-8167-01baf851e169
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Level_5 = ```
			
			VAR WBS4_Name = LOOKUPVALUE(
			    '03 XER_PROJWBS'[wbs_name],
			    '03 XER_PROJWBS'[wbs_id_key],
			    PATHITEM('03 XER_PROJWBS'[Path], 5)
			)
			RETURN
			    COALESCE(WBS4_Name, '03 XER_PROJWBS'[Level_4])
			
			```
		lineageTag: fec92be7-422f-44e9-b0e4-12ef257a6394
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column wbs_id_key
		dataType: string
		lineageTag: 3a27a59d-4b99-4bf7-86e5-7a5ea800570c
		summarizeBy: none
		sourceColumn: wbs_id_key

		annotation SummarizationSetBy = Automatic

	column parent_wbs_id_key
		dataType: string
		lineageTag: e13affb1-04d1-45d4-b82f-88970a968134
		summarizeBy: none
		sourceColumn: parent_wbs_id_key

		annotation SummarizationSetBy = Automatic

	column 'Min Start for Level 2' =
			
			VAR CurrentLevel2 = '03 XER_PROJWBS'[Level_2]
			RETURN
			CALCULATE(
			    MIN('01 XER_TASK'[Start]),
			    FILTER(
			        ALL('03 XER_PROJWBS'),
			        '03 XER_PROJWBS'[Level_2] = CurrentLevel2
			    )
			)
		formatString: dd/mm/yyyy
		lineageTag: 9dbbfd04-e0c8-4c0c-88f2-f8e482f4c265
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ProjectCode
		dataType: string
		lineageTag: 5a0c250b-75e8-481f-8458-7fd22b012dad
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column ProjectName = LOOKUPVALUE('01 XER_TASK'[ProjectName],'01 XER_TASK'[ProjectCode],'03 XER_PROJWBS'[ProjectCode])
		lineageTag: 3ee2cfee-4d02-411a-9833-4f75fc51028c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition '03 XER_PROJWBS' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("03_xer_projwbs"),
				
				    SelectedColumns =
				        Table.SelectColumns(
				            Source,
				            {
				                "wbs_name",
				                "wbs_id_key",
				                "parent_wbs_id_key",
				                "filename"
				            }
				        ),
				
				    AddProjectCode =
				        Table.AddColumn(
				            SelectedColumns,
				            "ProjectCode",
				            each
				                if [filename] <> null and Text.Contains([filename], "-") then
				                    Text.BeforeDelimiter([filename], "-")
				                else
				                    null,
				            type nullable text
				        ),
				
				    CleanParentWBS =
				        Table.TransformColumns(
				            AddProjectCode,
				            {
				                {
				                    "parent_wbs_id_key",
				                    each if _ = "" then null else _,
				                    type nullable text
				                }
				            }
				        ),
				
				    Final =
				        Table.SelectColumns(
				            CleanParentWBS,
				            {
				                "wbs_name",
				                "wbs_id_key",
				                "parent_wbs_id_key",
				                "ProjectCode"
				            }
				        )
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

