table '05 XER_DATA DATE'
	lineageTag: 7c6c4c55-1081-4ac6-83d2-06c7002e1eb7

	column last_recalc_date
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: 75a1cd96-44c2-4b47-92cc-b5e30d8af48f
		summarizeBy: none
		sourceColumn: last_recalc_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column proj_short_name
		dataType: string
		lineageTag: 1c89884c-d98a-4714-95e8-049f515d84e7
		summarizeBy: none
		sourceColumn: proj_short_name

		annotation SummarizationSetBy = Automatic

	column proj_id_key
		dataType: string
		lineageTag: d55de719-cda8-43b6-aa23-508f78a421ea
		summarizeBy: none
		sourceColumn: proj_id_key

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: c4704515-7d8e-4bba-86d2-f7262ebb3fc5
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	partition '05 XER_DATA DATE' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = Table.Buffer(#"02 XER_PROJECT"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"proj_short_name", "last_recalc_date", "proj_id_key", "filename"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

