table '06 XER_PREDECESSOR'
	lineageTag: 6c97f080-826d-44db-8576-0c805feced04

	column task_id_key
		dataType: string
		lineageTag: 413cd052-da64-489c-9ccb-a4ace2599412
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column pred_type
		dataType: string
		lineageTag: c41a1bf7-7c8b-498f-b239-42f4ba495eba
		summarizeBy: none
		sourceColumn: pred_type

		annotation SummarizationSetBy = Automatic

	column task_code = RELATED('01 XER_TASK'[task_code])
		lineageTag: b81e33c5-66e8-422a-8d6c-340fee286d42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column remaining_duration = RELATED('01 XER_TASK'[remaining_duration])
		formatString: 0
		lineageTag: 8345b7c4-f7f0-4743-abf5-85b9faec79f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Variance to Baseline' = RELATED('01 XER_TASK'[Variance_Finish_BL])
		formatString: 0
		lineageTag: 9d9cebcf-7e56-4af4-a443-857602730001
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Variance to Previous Month' = RELATED('01 XER_TASK'[Finish_Variance_Previous_Month])
		formatString: 0
		lineageTag: cc63d83c-ebf8-4e85-a31d-286a63af2300
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TaskCodeAndName =
			
			VAR _taskCode = RELATED('01 XER_TASK'[task_code])
			VAR _taskName = RELATED('01 XER_TASK'[task_name])
			RETURN
			    _taskCode & " - " & _taskName
		lineageTag: b6d53fc7-0751-4f43-a8cc-c36dd9fbab0c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column predecessor_task_code = LOOKUPVALUE('01 XER_TASK'[task_code],'01 XER_TASK'[Task_ID_key],[pred_task_id_key])
		lineageTag: f6f3a806-3c26-44ba-b90b-880b9a7eb127
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Baseline Start' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			
			RETURN
			    MAXX(
			        FILTER(
			            ALL('04 XER_BASELINE'),
			            '04 XER_BASELINE'[task_code] = CurrentTaskCode &&
			            '04 XER_BASELINE'[ProjectCode] = CurrentProject
			        ),
			        '04 XER_BASELINE'[early_start_date]
			    )
		lineageTag: 4437b4bd-ccc3-45ee-aa72-74825c4fd048
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline Finish' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			
			RETURN
			    MAXX(
			        FILTER(
			            ALL('04 XER_BASELINE'),
			            '04 XER_BASELINE'[task_code] = CurrentTaskCode &&
			            '04 XER_BASELINE'[ProjectCode] = CurrentProject
			        ),
			        '04 XER_BASELINE'[early_end_date]
			    )
		lineageTag: 523861ed-a746-484b-87f0-36c627742b32
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Previous Update Start' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			VAR CurrentMonthUpdate = '06 XER_PREDECESSOR'[UpdateDate]
			-- Find the previous month update (closest but less than current)
			VAR PreviousMonthUpdate =
			CALCULATE(
			MAX('01 XER_TASK'[UpdateDate]),
			FILTER(
			ALL('01 XER_TASK'),
			'01 XER_TASK'[task_code] = CurrentTaskCode &&
			'01 XER_TASK'[ProjectCode] = CurrentProject &&
			'01 XER_TASK'[UpdateDate] < CurrentMonthUpdate
			)
			)
			-- Get the Start date from the previous month update
			RETURN
			CALCULATE(
			MAX('01 XER_TASK'[early_start_date]),
			FILTER(
			ALL('01 XER_TASK'),
			'01 XER_TASK'[task_code] = CurrentTaskCode &&
			'01 XER_TASK'[ProjectCode] = CurrentProject &&
			'01 XER_TASK'[UpdateDate] = PreviousMonthUpdate
			)
			)
		formatString: dd/mm/yyyy
		lineageTag: 1eabe51d-e8c4-4329-a971-0d89b1f10c71
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Previous Update Finish' = ```
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			VAR CurrentMonthUpdate = '06 XER_PREDECESSOR'[UpdateDate]
			
			-- Find the previous month update (closest but less than current)
			VAR PreviousMonthUpdate = 
			    CALCULATE(
			        MAX('01 XER_TASK'[UpdateDate]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_code] = CurrentTaskCode &&
			            '01 XER_TASK'[ProjectCode] = CurrentProject &&
			            '01 XER_TASK'[UpdateDate] < CurrentMonthUpdate
			        )
			    )
			
			-- Get the Start date from the previous month update
			RETURN
			    CALCULATE(
			        MAX('01 XER_TASK'[early_end_date]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_code] = CurrentTaskCode &&
			            '01 XER_TASK'[ProjectCode] = CurrentProject &&
			            '01 XER_TASK'[UpdateDate] = PreviousMonthUpdate
			        )
			    )
			```
		formatString: dd/mm/yyyy
		lineageTag: 0b0776b0-4580-474d-9450-afe4210a8ac1
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Successor_Level_2 = ```
			
			VAR SuccTaskID = '06 XER_PREDECESSOR'[task_id_key]
			VAR SuccessorWBS_ID = 
			    CALCULATE(
			        SELECTEDVALUE('01 XER_TASK'[wbs_id_key]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_id_key] = SuccTaskID
			        )
			    )
			VAR SuccLevel2 = 
			    IF(
			        NOT ISBLANK(SuccessorWBS_ID),
			        CALCULATE(
			            MINX(
			                FILTER(
			                    ALL('03 XER_PROJWBS'),
			                    '03 XER_PROJWBS'[wbs_id_key] = SuccessorWBS_ID
			                ),
			                '03 XER_PROJWBS'[Level_2]
			            )
			        )
			    )
			RETURN
			    SuccLevel2
			```
		lineageTag: edd8bac4-29f2-4178-9030-2130db1006ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Predecessor_Level_2 = ```
			
			VAR PredTaskID = '06 XER_PREDECESSOR'[pred_task_id_key]
			VAR PredecessorWBS_ID = 
			    CALCULATE(
			        SELECTEDVALUE('01 XER_TASK'[wbs_id_key]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_id_key] = PredTaskID
			        )
			    )
			VAR PredLevel2 = 
			    IF(
			        NOT ISBLANK(PredecessorWBS_ID),
			        CALCULATE(
			            MINX(
			                FILTER(
			                    ALL('03 XER_PROJWBS'),
			                    '03 XER_PROJWBS'[wbs_id_key] = PredecessorWBS_ID
			                ),
			                '03 XER_PROJWBS'[Level_2]
			            )
			        )
			    )
			RETURN
			    PredLevel2
			```
		lineageTag: 1cfa0aa8-f050-434a-8ad5-40c9f5725f1f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Link_Type =
			
			IF(
			    '06 XER_PREDECESSOR'[Successor_Level_2] = '06 XER_PREDECESSOR'[Predecessor_Level_2],
			    "Internal Link",
			    "Cross-WBS Link"
			)
		lineageTag: 95640178-8db4-4f4c-8273-243f59583603
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column WBS_Link_Direction =
			
			'06 XER_PREDECESSOR'[Predecessor_Level_2] & " → " & '06 XER_PREDECESSOR'[Successor_Level_2]
		lineageTag: de16278c-97f0-4bd4-86cc-fc20a5bfd566
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CriticalLink = ```
			
			VAR crit_succ = 
			    LOOKUPVALUE(
			        '01 XER_TASK'[CriticalStatus],
			        '01 XER_TASK'[task_id_key], '06 XER_PREDECESSOR'[task_id_key]
			    )
			VAR crit_pred = 
			    LOOKUPVALUE(
			        '01 XER_TASK'[CriticalStatus],
			        '01 XER_TASK'[task_id_key], '06 XER_PREDECESSOR'[pred_task_id_key]
			    )
			RETURN
			    IF(
			        NOT(ISBLANK(crit_pred)) && NOT(ISBLANK(crit_succ)),
			        crit_pred & " → " & crit_succ,
			        BLANK()
			    )
			```
		lineageTag: d5223047-9831-495c-a6a7-7598adab917f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Driving Predecessor' =
			
			VAR CurrentTaskID = '06 XER_PREDECESSOR'[task_id_key]
			VAR CurrentFreeFloat = '06 XER_PREDECESSOR'[free_float]
			
			VAR MinFreeFloatForTask =
			    CALCULATE (
			        MIN ( '06 XER_PREDECESSOR'[free_float] ),
			        FILTER (
			            ALL ( '06 XER_PREDECESSOR' ),
			            '06 XER_PREDECESSOR'[task_id_key] = CurrentTaskID
			        )
			    )
			
			RETURN
			    IF (
			        NOT ISBLANK ( CurrentFreeFloat ) && CurrentFreeFloat = MinFreeFloatForTask,
			        "Driving",
			        "Not Driving"
			    )
		lineageTag: 9c5ebbb1-dcd8-402b-861b-3e4b5fd11321
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Type Validity' =
			
			VAR taskType = '06 XER_PREDECESSOR'[task_type]
			VAR predTaskType = '06 XER_PREDECESSOR'[predecessor_task_type]
			VAR invalidTypes = { "TT_WBS", "TT_LOE" }
			
			RETURN
			    IF (
			        taskType IN invalidTypes || predTaskType IN invalidTypes,
			        "Invalid",
			        "Valid"
			    )
		lineageTag: 10c66ca2-309a-4bc6-bc92-0f0c44b0d730
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a443bd6-b8e6-417e-a831-88df7b76d505
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column early_start_date = related('01 XER_TASK'[early_start_date])
		formatString: dd/mm/yyyy
		lineageTag: 19d14697-ab4d-4ced-8b77-7be4c3a78d19
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column early_end_date = related('01 XER_TASK'[early_end_date])
		formatString: dd/mm/yyyy
		lineageTag: 8979992a-8a41-4da9-ae17-37f2cf9957fb
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ProjectCode
		dataType: string
		lineageTag: 559d3191-e1d5-45b6-b610-54608f4c4b7c
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column predecessor_status_code
		dataType: string
		lineageTag: 3637482a-d2d3-4a61-bfa5-b3bec6d23e51
		summarizeBy: none
		sourceColumn: predecessor_status_code

		annotation SummarizationSetBy = Automatic

	column task_type
		dataType: string
		lineageTag: 46178a8a-cfeb-4d5f-b885-cfea597ffa05
		summarizeBy: none
		sourceColumn: task_type

		annotation SummarizationSetBy = Automatic

	column predecessor_task_type
		dataType: string
		lineageTag: a261abba-88dd-45ec-981f-1a2624cfc0ac
		summarizeBy: none
		sourceColumn: predecessor_task_type

		annotation SummarizationSetBy = Automatic

	column lag
		dataType: double
		lineageTag: fe0d1768-553c-4dbb-832e-6bd6201c8c37
		summarizeBy: sum
		sourceColumn: lag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column start
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0111cd41-c633-4ee4-b53b-15335bf96b5a
		summarizeBy: none
		sourceColumn: start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column finish
		dataType: dateTime
		formatString: Long Date
		lineageTag: 062b45b4-0b20-4eb5-807f-8cb21fb21f47
		summarizeBy: none
		sourceColumn: finish

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column predecessor_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: 485def26-ab97-4bb8-9621-16ce13548840
		summarizeBy: none
		sourceColumn: predecessor_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column predecessor_finish
		dataType: dateTime
		formatString: Long Date
		lineageTag: e525075f-c1c4-4c71-a023-a9d9101f490a
		summarizeBy: none
		sourceColumn: predecessor_finish

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column free_float
		dataType: double
		lineageTag: 6d4de28d-5fc9-4954-8983-31e8ae35443c
		summarizeBy: sum
		sourceColumn: free_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pred_task_id_key
		dataType: string
		lineageTag: fa5ed2b6-bdcb-4e95-a0fd-ff82c80f7ed0
		summarizeBy: none
		sourceColumn: pred_task_id_key

		annotation SummarizationSetBy = Automatic

	column status_code
		dataType: string
		lineageTag: 659f26be-3f23-4225-9527-db386da77ef2
		summarizeBy: none
		sourceColumn: status_code

		annotation SummarizationSetBy = Automatic

	column total_float
		dataType: double
		lineageTag: 81036ff5-a54a-4a53-aabc-5127aba7f20d
		summarizeBy: sum
		sourceColumn: total_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column task_pred_id_key
		dataType: string
		lineageTag: 2ab7e73e-18fa-44cf-8829-a5c520d1547e
		summarizeBy: none
		sourceColumn: task_pred_id_key

		annotation SummarizationSetBy = Automatic

	column PredTaskCodeAndName =
			
			VAR _taskCode = LOOKUPVALUE('01 XER_TASK'[task_code],'01 XER_TASK'[task_id_key],'06 XER_PREDECESSOR'[pred_task_id_key])
			VAR _taskName = LOOKUPVALUE('01 XER_TASK'[task_name],'01 XER_TASK'[task_id_key],'06 XER_PREDECESSOR'[pred_task_id_key])
			RETURN
			    _taskCode & " - " & _taskName
		lineageTag: ed994dd3-ba8c-4533-a6a9-3dcbeb5dc32e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'predecessor_Total Float' = LOOKUPVALUE('01 XER_TASK'[total_float],'01 XER_TASK'[Task_ID_key],[pred_task_id_key])
		lineageTag: 3ef7601a-6708-462b-95c2-9e65e33cb7a2
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '06 XER_PREDECESSOR' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("06_xer_predecessor"),
				
				    SelectedColumns =
				        Table.SelectColumns(Source,{"task_pred_id", "pred_type", "task_id_key", "pred_task_id_key", "status_code", "predecessor_status_code", "task_type", "predecessor_task_type", "lag", "start", "finish", "predecessor_start", "predecessor_finish", "free_float", "total_float", "filename"}),
				    #"Inserted Merged Column" = Table.AddColumn(SelectedColumns, "task_pred_id_key", each Text.Combine({[filename], [task_pred_id]}, "."), type text),
				
				    AddParsedColumns =
				        Table.ExpandRecordColumn(
				            Table.AddColumn(
				                #"Inserted Merged Column",
				                "Parsed",
				                each
				                    let
				                        FileName =
				                            if [filename] = null then
				                                null
				                            else
				                                Text.Trim([filename]),
				
				                        Prefix =
				                            if FileName <> null and Text.Contains(FileName, "_") then
				                                Text.BeforeDelimiter(FileName, "_")
				                            else
				                                FileName,
				
				                        Parts =
				                            if Prefix <> null then
				                                Text.Split(Prefix, "-")
				                            else
				                                {},
				
				                        ProjectCode =
				                            if List.Count(Parts) >= 1 then
				                                Parts{0}
				                            else
				                                null,
				
				                        CPart =
				                            if List.Count(Parts) >= 3 then
				                                Parts{2}
				                            else
				                                null,
				
				                        UpdateDate =
				                            if CPart = null or CPart = "" then
				                                null
				                            else if Text.StartsWith(CPart, "BL") then
				                                let
				                                    DatePart =
				                                        if FileName <> null and Text.Contains(FileName, "_") then
				                                            try Text.BeforeDelimiter(Text.AfterDelimiter(FileName, "_"), ".") otherwise null
				                                        else
				                                            null
				                                in
				                                    try Date.EndOfMonth(Date.From(DateTime.FromText(DatePart))) otherwise null
				                            else
				                                let
				                                    P1 = try Number.FromText(Text.Start(CPart, 2)) otherwise null,
				                                    P2 = try Number.FromText(Text.End(CPart, 2)) otherwise null,
				                                    Yr = if P1 = null or P2 = null then null else if P2 > 12 then P2 else P1,
				                                    Mo = if P1 = null or P2 = null then null else if P2 > 12 then P1 else P2
				                                in
				                                    if Yr = null or Mo = null or Mo < 1 or Mo > 12 then
				                                        null
				                                    else
				                                        Date.EndOfMonth(#date(2000 + Yr, Mo, 1))
				                    in
				                        [
				                            ProjectCode = ProjectCode,
				                            UpdateDate = UpdateDate
				                        ],
				                type [
				                    ProjectCode = nullable text,
				                    UpdateDate = nullable date
				                ]
				            ),
				            "Parsed",
				            {"ProjectCode", "UpdateDate"},
				            {"ProjectCode", "UpdateDate"}
				        ),
				    #"Parsed Date" = Table.TransformColumns(AddParsedColumns,{{"start", each Date.From(DateTimeZone.From(_)), type date}, {"finish", each Date.From(DateTimeZone.From(_)), type date}, {"predecessor_start", each Date.From(DateTimeZone.From(_)), type date}, {"predecessor_finish", each Date.From(DateTimeZone.From(_)), type date}}),
				
				    Typed =
				        Table.TransformColumnTypes(
				            #"Parsed Date",
				            {
				                {"lag", type number},
				                {"free_float", type number},
				                {"total_float", type number},
				                {"UpdateDate", type date}
				            }
				        ),
				    #"Removed Columns" = Table.RemoveColumns(Typed,{"task_pred_id", "filename"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

