table '06 XER_PREDECESSOR'
	lineageTag: 6c97f080-826d-44db-8576-0c805feced04

	column lag_hr_cnt
		dataType: string
		lineageTag: 21dcf587-15da-4090-817b-418823107ea8
		summarizeBy: none
		sourceColumn: lag_hr_cnt

		annotation SummarizationSetBy = Automatic

	column task_id_key
		dataType: string
		lineageTag: 413cd052-da64-489c-9ccb-a4ace2599412
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column pred_task_id_key
		dataType: string
		lineageTag: 4af8f8c9-5f9e-4aa0-b6b6-a1d4e38d1462
		summarizeBy: none
		sourceColumn: pred_task_id_key

		annotation SummarizationSetBy = Automatic

	column pred_type
		dataType: string
		lineageTag: c41a1bf7-7c8b-498f-b239-42f4ba495eba
		summarizeBy: none
		sourceColumn: pred_type

		annotation SummarizationSetBy = Automatic

	column task_code = RELATED('01 XER_TASK'[task_code])
		lineageTag: b81e33c5-66e8-422a-8d6c-340fee286d42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column remaining_duration = RELATED('01 XER_TASK'[remaining_duration])
		formatString: 0
		lineageTag: 8345b7c4-f7f0-4743-abf5-85b9faec79f8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Variance to Baseline' = RELATED('01 XER_TASK'[Variance_Finish_BL])
		formatString: 0
		lineageTag: 9d9cebcf-7e56-4af4-a443-857602730001
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Variance to Previous Month' = RELATED('01 XER_TASK'[Finish_Variance_Previous_Month])
		formatString: 0
		lineageTag: cc63d83c-ebf8-4e85-a31d-286a63af2300
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TaskCodeAndName =
			
			VAR _taskCode = RELATED('01 XER_TASK'[task_code])
			VAR _taskName = RELATED('01 XER_TASK'[task_name])
			RETURN
			    _taskCode & " - " & _taskName
		lineageTag: b6d53fc7-0751-4f43-a8cc-c36dd9fbab0c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Total Float' = RELATED('01 XER_TASK'[total_float])
		formatString: 0
		lineageTag: e14ca113-edc2-4687-9253-81df78ea22a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column predecessor_task_code = LOOKUPVALUE('01 XER_TASK'[task_code],'01 XER_TASK'[Task_ID_key],[pred_task_id_key])
		lineageTag: f6f3a806-3c26-44ba-b90b-880b9a7eb127
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Baseline Start' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			
			RETURN
			    MAXX(
			        FILTER(
			            ALL('04 XER_BASELINE'),
			            '04 XER_BASELINE'[task_code] = CurrentTaskCode &&
			            '04 XER_BASELINE'[ProjectCode] = CurrentProject
			        ),
			        '04 XER_BASELINE'[early_start_date]
			    )
		lineageTag: 4437b4bd-ccc3-45ee-aa72-74825c4fd048
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline Finish' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			
			RETURN
			    MAXX(
			        FILTER(
			            ALL('04 XER_BASELINE'),
			            '04 XER_BASELINE'[task_code] = CurrentTaskCode &&
			            '04 XER_BASELINE'[ProjectCode] = CurrentProject
			        ),
			        '04 XER_BASELINE'[early_end_date]
			    )
		lineageTag: 523861ed-a746-484b-87f0-36c627742b32
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Previous Update Start' =
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			VAR CurrentMonthUpdate = '06 XER_PREDECESSOR'[UpdateDate]
			-- Find the previous month update (closest but less than current)
			VAR PreviousMonthUpdate =
			CALCULATE(
			MAX('01 XER_TASK'[UpdateDate]),
			FILTER(
			ALL('01 XER_TASK'),
			'01 XER_TASK'[task_code] = CurrentTaskCode &&
			'01 XER_TASK'[ProjectCode] = CurrentProject &&
			'01 XER_TASK'[UpdateDate] < CurrentMonthUpdate
			)
			)
			-- Get the Start date from the previous month update
			RETURN
			CALCULATE(
			MAX('01 XER_TASK'[early_start_date]),
			FILTER(
			ALL('01 XER_TASK'),
			'01 XER_TASK'[task_code] = CurrentTaskCode &&
			'01 XER_TASK'[ProjectCode] = CurrentProject &&
			'01 XER_TASK'[UpdateDate] = PreviousMonthUpdate
			)
			)
		formatString: dd/mm/yyyy
		lineageTag: 1eabe51d-e8c4-4329-a971-0d89b1f10c71
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Previous Update Finish' = ```
			
			VAR CurrentTaskCode = '06 XER_PREDECESSOR'[task_code]
			VAR CurrentProject = '06 XER_PREDECESSOR'[ProjectCode]
			VAR CurrentMonthUpdate = '06 XER_PREDECESSOR'[UpdateDate]
			
			-- Find the previous month update (closest but less than current)
			VAR PreviousMonthUpdate = 
			    CALCULATE(
			        MAX('01 XER_TASK'[UpdateDate]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_code] = CurrentTaskCode &&
			            '01 XER_TASK'[ProjectCode] = CurrentProject &&
			            '01 XER_TASK'[UpdateDate] < CurrentMonthUpdate
			        )
			    )
			
			-- Get the Start date from the previous month update
			RETURN
			    CALCULATE(
			        MAX('01 XER_TASK'[early_end_date]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_code] = CurrentTaskCode &&
			            '01 XER_TASK'[ProjectCode] = CurrentProject &&
			            '01 XER_TASK'[UpdateDate] = PreviousMonthUpdate
			        )
			    )
			```
		formatString: dd/mm/yyyy
		lineageTag: 0b0776b0-4580-474d-9450-afe4210a8ac1
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Successor_Level_2 = ```
			
			VAR SuccTaskID = '06 XER_PREDECESSOR'[task_id_key]
			VAR SuccessorWBS_ID = 
			    CALCULATE(
			        SELECTEDVALUE('01 XER_TASK'[wbs_id_key]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_id_key] = SuccTaskID
			        )
			    )
			VAR SuccLevel2 = 
			    IF(
			        NOT ISBLANK(SuccessorWBS_ID),
			        CALCULATE(
			            MINX(
			                FILTER(
			                    ALL('03 XER_PROJWBS'),
			                    '03 XER_PROJWBS'[wbs_id_key] = SuccessorWBS_ID
			                ),
			                '03 XER_PROJWBS'[Level_2]
			            )
			        )
			    )
			RETURN
			    SuccLevel2
			```
		lineageTag: edd8bac4-29f2-4178-9030-2130db1006ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Predecessor_Level_2 = ```
			
			VAR PredTaskID = '06 XER_PREDECESSOR'[pred_task_id_key]
			VAR PredecessorWBS_ID = 
			    CALCULATE(
			        SELECTEDVALUE('01 XER_TASK'[wbs_id_key]),
			        FILTER(
			            ALL('01 XER_TASK'),
			            '01 XER_TASK'[task_id_key] = PredTaskID
			        )
			    )
			VAR PredLevel2 = 
			    IF(
			        NOT ISBLANK(PredecessorWBS_ID),
			        CALCULATE(
			            MINX(
			                FILTER(
			                    ALL('03 XER_PROJWBS'),
			                    '03 XER_PROJWBS'[wbs_id_key] = PredecessorWBS_ID
			                ),
			                '03 XER_PROJWBS'[Level_2]
			            )
			        )
			    )
			RETURN
			    PredLevel2
			```
		lineageTag: 1cfa0aa8-f050-434a-8ad5-40c9f5725f1f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Link_Type =
			
			IF(
			    '06 XER_PREDECESSOR'[Successor_Level_2] = '06 XER_PREDECESSOR'[Predecessor_Level_2],
			    "Internal Link",
			    "Cross-WBS Link"
			)
		lineageTag: 95640178-8db4-4f4c-8273-243f59583603
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column WBS_Link_Direction =
			
			'06 XER_PREDECESSOR'[Predecessor_Level_2] & " → " & '06 XER_PREDECESSOR'[Successor_Level_2]
		lineageTag: de16278c-97f0-4bd4-86cc-fc20a5bfd566
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column PredTaskCodeAndName =
			
			VAR _taskCode = LOOKUPVALUE('01 XER_TASK'[task_code],'01 XER_TASK'[task_id_key],'06 XER_PREDECESSOR'[pred_task_id_key])
			VAR _taskName = LOOKUPVALUE('01 XER_TASK'[task_name],'01 XER_TASK'[task_id_key],'06 XER_PREDECESSOR'[pred_task_id_key])
			RETURN
			    _taskCode & " - " & _taskName
		lineageTag: 24353972-bb3b-4b28-86f3-55cc2ef440cb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CriticalLink = ```
			
			VAR crit_succ = 
			    LOOKUPVALUE(
			        '01 XER_TASK'[CriticalStatus],
			        '01 XER_TASK'[task_id_key], '06 XER_PREDECESSOR'[task_id_key]
			    )
			VAR crit_pred = 
			    LOOKUPVALUE(
			        '01 XER_TASK'[CriticalStatus],
			        '01 XER_TASK'[task_id_key], '06 XER_PREDECESSOR'[pred_task_id_key]
			    )
			RETURN
			    IF(
			        NOT(ISBLANK(crit_pred)) && NOT(ISBLANK(crit_succ)),
			        crit_pred & " → " & crit_succ,
			        BLANK()
			    )
			```
		lineageTag: d5223047-9831-495c-a6a7-7598adab917f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Is Driving Predecessor' =
			
			VAR CurrentTaskID = '06 XER_PREDECESSOR'[task_id_key]
			VAR CurrentFreeFloat = '06 XER_PREDECESSOR'[free_float]
			
			VAR MinFreeFloatForTask =
			    CALCULATE (
			        MIN ( '06 XER_PREDECESSOR'[free_float] ),
			        FILTER (
			            ALL ( '06 XER_PREDECESSOR' ),
			            '06 XER_PREDECESSOR'[task_id_key] = CurrentTaskID
			        )
			    )
			
			RETURN
			    IF (
			        NOT ISBLANK ( CurrentFreeFloat ) && CurrentFreeFloat = MinFreeFloatForTask,
			        "Driving",
			        "Not Driving"
			    )
		lineageTag: 9c5ebbb1-dcd8-402b-861b-3e4b5fd11321
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Type Validity' =
			
			VAR taskType = '06 XER_PREDECESSOR'[task_type]
			VAR predTaskType = '06 XER_PREDECESSOR'[predecessor_task_type]
			VAR invalidTypes = { "TT_WBS", "TT_LOE" }
			
			RETURN
			    IF (
			        taskType IN invalidTypes || predTaskType IN invalidTypes,
			        "Invalid",
			        "Valid"
			    )
		lineageTag: 10c66ca2-309a-4bc6-bc92-0f0c44b0d730
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'predecessor_Total Float' = LOOKUPVALUE('01 XER_TASK'[total_float],'01 XER_TASK'[Task_ID_key],[pred_task_id_key])
		formatString: 0
		lineageTag: f364cc56-9492-4ea2-bad0-53ec4f4b39e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column predecessor_name = LOOKUPVALUE('01 XER_TASK'[task_name],'01 XER_TASK'[Task_ID_key],[pred_task_id_key])
		lineageTag: c3df4ebf-7cfd-4fa7-8210-d00d460d86f4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column server
		dataType: string
		lineageTag: bfc2bab3-47c4-4823-8753-40f5c3a73882
		summarizeBy: none
		sourceColumn: server

		annotation SummarizationSetBy = Automatic

	column database
		dataType: string
		lineageTag: 8743b239-cb2a-4353-b143-a2cf8e865498
		summarizeBy: none
		sourceColumn: database

		annotation SummarizationSetBy = Automatic

	column task_pred_id
		dataType: string
		lineageTag: 13ee31c8-8451-4e94-afc6-e414855a6db4
		summarizeBy: none
		sourceColumn: task_pred_id

		annotation SummarizationSetBy = Automatic

	column task_id
		dataType: string
		lineageTag: ab5d69b9-59fe-4ec2-96db-8bb88d1c746b
		summarizeBy: none
		sourceColumn: task_id

		annotation SummarizationSetBy = Automatic

	column pred_task_id
		dataType: string
		lineageTag: f3afc86e-69f0-472d-89b8-e32301137613
		summarizeBy: none
		sourceColumn: pred_task_id

		annotation SummarizationSetBy = Automatic

	column proj_id
		dataType: string
		lineageTag: 6105b684-dc3a-4b2b-831e-714e100de3bd
		summarizeBy: none
		sourceColumn: proj_id

		annotation SummarizationSetBy = Automatic

	column pred_proj_id
		dataType: string
		lineageTag: 922a13ba-49d8-44f9-808e-38089a4f1c4c
		summarizeBy: none
		sourceColumn: pred_proj_id

		annotation SummarizationSetBy = Automatic

	column comments
		dataType: string
		lineageTag: b22a1146-a439-4671-82de-09e0616371ec
		summarizeBy: none
		sourceColumn: comments

		annotation SummarizationSetBy = Automatic

	column float_path
		dataType: string
		lineageTag: 1c54a882-50d7-430d-aae4-ec7c16d79854
		summarizeBy: none
		sourceColumn: float_path

		annotation SummarizationSetBy = Automatic

	column aref
		dataType: dateTime
		formatString: Long Date
		lineageTag: 44a4709f-e964-400d-be8e-1fbd1285aa3f
		summarizeBy: none
		sourceColumn: aref

		annotation SummarizationSetBy = Automatic

	column arls
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e81c44e-3788-4b56-a929-4465206213f2
		summarizeBy: none
		sourceColumn: arls

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: e74ff897-e07c-4684-af42-91fd42093472
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2cde1828-8e1c-4346-bbfe-0eaf15d857a2
		summarizeBy: none
		sourceColumn: refresh_date

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a443bd6-b8e6-417e-a831-88df7b76d505
		summarizeBy: none
		sourceColumn: UpdateDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column early_start_date = related('01 XER_TASK'[early_start_date])
		formatString: dd/mm/yyyy
		lineageTag: 19d14697-ab4d-4ced-8b77-7be4c3a78d19
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column early_end_date = related('01 XER_TASK'[early_end_date])
		formatString: dd/mm/yyyy
		lineageTag: 8979992a-8a41-4da9-ae17-37f2cf9957fb
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column status_code_successor = RELATED('01 XER_TASK'[status_code])
		lineageTag: a1b2c3d4-1111-4aaa-bbbb-000000000001
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column clndr_id_key = RELATED('01 XER_TASK'[calendar_id_key])
		lineageTag: a1b2c3d4-1111-4aaa-bbbb-000000000007
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: 559d3191-e1d5-45b6-b610-54608f4c4b7c
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column calendar_id_key
		dataType: string
		lineageTag: f32e219a-19f2-4390-bbbf-a0f4ee16844a
		summarizeBy: none
		sourceColumn: calendar_id_key

		annotation SummarizationSetBy = Automatic

	column predecessor_clndr_id_key
		dataType: string
		lineageTag: e43ac4bc-e756-4090-9228-047b9be7a71a
		summarizeBy: none
		sourceColumn: predecessor_clndr_id_key

		annotation SummarizationSetBy = Automatic

	column status_code
		dataType: string
		lineageTag: 5e92998f-aba3-4fb3-9b5f-829777232436
		summarizeBy: none
		sourceColumn: status_code

		annotation SummarizationSetBy = Automatic

	column predecessor_status_code
		dataType: string
		lineageTag: 3637482a-d2d3-4a61-bfa5-b3bec6d23e51
		summarizeBy: none
		sourceColumn: predecessor_status_code

		annotation SummarizationSetBy = Automatic

	column task_type
		dataType: string
		lineageTag: 46178a8a-cfeb-4d5f-b885-cfea597ffa05
		summarizeBy: none
		sourceColumn: task_type

		annotation SummarizationSetBy = Automatic

	column predecessor_task_type
		dataType: string
		lineageTag: a261abba-88dd-45ec-981f-1a2624cfc0ac
		summarizeBy: none
		sourceColumn: predecessor_task_type

		annotation SummarizationSetBy = Automatic

	column lag
		dataType: double
		lineageTag: fe0d1768-553c-4dbb-832e-6bd6201c8c37
		summarizeBy: sum
		sourceColumn: lag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column time_period_hours_per_day
		dataType: double
		lineageTag: c178e389-fc4f-470f-8d39-d4b8cb16e401
		summarizeBy: sum
		sourceColumn: time_period_hours_per_day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column start
		dataType: dateTime
		formatString: General Date
		lineageTag: 0111cd41-c633-4ee4-b53b-15335bf96b5a
		summarizeBy: none
		sourceColumn: start

		annotation SummarizationSetBy = Automatic

	column finish
		dataType: dateTime
		formatString: General Date
		lineageTag: 062b45b4-0b20-4eb5-807f-8cb21fb21f47
		summarizeBy: none
		sourceColumn: finish

		annotation SummarizationSetBy = Automatic

	column predecessor_start
		dataType: dateTime
		formatString: General Date
		lineageTag: 485def26-ab97-4bb8-9621-16ce13548840
		summarizeBy: none
		sourceColumn: predecessor_start

		annotation SummarizationSetBy = Automatic

	column predecessor_finish
		dataType: dateTime
		formatString: General Date
		lineageTag: e525075f-c1c4-4c71-a023-a9d9101f490a
		summarizeBy: none
		sourceColumn: predecessor_finish

		annotation SummarizationSetBy = Automatic

	column free_float
		dataType: double
		lineageTag: 6d4de28d-5fc9-4954-8983-31e8ae35443c
		summarizeBy: sum
		sourceColumn: free_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_float
		dataType: double
		lineageTag: 75867e6a-f400-4588-8178-94b00b22d20a
		summarizeBy: sum
		sourceColumn: total_float

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column monthupdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff9111a5-7db0-46ce-bd4e-1275190aea5f
		summarizeBy: none
		sourceColumn: monthupdate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition '06 XER_PREDECESSOR' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("06_xer_predecessor"),
				
				    AddParsedColumns = Table.AddColumn(
				        Table.AddColumn(Source, "ProjectCode", each Text.BeforeDelimiter([filename], "-"), type text),
				        "UpdateDate", each
				            let
				                parts = Text.Split(Text.BeforeDelimiter([filename], "_"), "-"),
				                cPart = if List.Count(parts) >= 3 then parts{2} else "",
				                datePart = Text.BeforeDelimiter(Text.AfterDelimiter([filename], "_"), ".")
				            in
				                if Text.StartsWith(cPart, "BL") then
				                    Date.EndOfMonth(Date.FromText(datePart))
				                else
				                    let
				                        p1 = Number.FromText(Text.Start(cPart, 2)),
				                        p2 = Number.FromText(Text.End(cPart, 2)),
				                        yr = if p2 > 12 then p2 else p1,
				                        mo = if p2 > 12 then p1 else p2
				                    in
				                        Date.EndOfMonth(#date(2000 + yr, mo, 1)),
				        type date
				    ),
				
				    Typed = Table.TransformColumnTypes(AddParsedColumns, {
				        {"refresh_date", type datetime}, {"arls", type datetime}, {"aref", type datetime},
				        {"start", type datetime}, {"finish", type datetime},
				        {"predecessor_start", type datetime}, {"predecessor_finish", type datetime},
				        {"free_float", type number}, {"total_float", type number},
				        {"time_period_hours_per_day", type number}, {"lag", type number},
				        {"monthupdate", type date}
				    })
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

