table '07 XER_ACTVTYPE'
	lineageTag: a20352d7-2126-4b85-a8c7-2d39fe44994f

	column actv_code_type_id_key
		dataType: string
		lineageTag: 9fa7cb4a-db95-4075-ae03-3f92ad21a950
		summarizeBy: none
		sourceColumn: actv_code_type_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_type
		dataType: string
		lineageTag: c4424bd7-3150-4338-8cdf-b832f61c8760
		summarizeBy: none
		sourceColumn: actv_code_type

		annotation SummarizationSetBy = Automatic

	partition '07 XER_ACTVTYPE' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("07_xer_actvtype"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"actv_code_type", "actv_code_type_id_key"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

