table '07 XER_ACTVTYPE'
	lineageTag: a20352d7-2126-4b85-a8c7-2d39fe44994f

	column actv_code_type_id_key
		dataType: string
		lineageTag: 9fa7cb4a-db95-4075-ae03-3f92ad21a950
		summarizeBy: none
		sourceColumn: actv_code_type_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_type
		dataType: string
		lineageTag: c4424bd7-3150-4338-8cdf-b832f61c8760
		summarizeBy: none
		sourceColumn: actv_code_type

		annotation SummarizationSetBy = Automatic

	column IsCsvSource
		dataType: boolean
		isHidden
		lineageTag: 117b84a5-2ca8-486a-89c3-4062c97b30d7
		summarizeBy: none
		sourceColumn: IsCsvSource

		annotation SummarizationSetBy = Automatic

	partition '07 XER_ACTVTYPE' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("07_xer_actvtype", "t.""actv_code_type"", t.""actv_code_type_id_key"""),
				    ContractColumns = Record.Field(XerCsvTableContracts, "07_XER_ACTVTYPE")[Columns],
				    ModelColumns = List.Combine({ContractColumns, {"IsCsvSource"}}),
				    AthenaFinal = Table.SelectColumns(Source, ContractColumns),
				    AthenaBranch = if XerCsvRouting[HasAthenaProjects] then Table.AddColumn(AthenaFinal, "IsCsvSource", each false, type logical) else Table.AddColumn(fnXerCsvEmptyTable("07_XER_ACTVTYPE"), "IsCsvSource", each false, type logical),
				    Combined = if XerCsvRouting[IsActive] then Table.Combine({AthenaBranch, fnXerCsvLoadTable("07_XER_ACTVTYPE")}) else AthenaBranch,
				    Final = Table.SelectColumns(Combined, ModelColumns)
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

