table '08 XER_ACTVCODE'
	lineageTag: 94c1fcbc-2867-47c1-a3a4-33f0b7591422

	column actv_code_id_key
		dataType: string
		lineageTag: aa91c058-ab23-4be7-8598-2ba4fb95fab6
		summarizeBy: none
		sourceColumn: actv_code_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_name
		dataType: string
		lineageTag: 49f9a270-6cca-4b11-8262-e3fa75cda5cb
		summarizeBy: none
		sourceColumn: actv_code_name

		annotation SummarizationSetBy = Automatic

	column actv_code_type_id_key
		dataType: string
		lineageTag: 374da73c-74e8-4109-b795-29961460ebff
		summarizeBy: none
		sourceColumn: actv_code_type_id_key

		annotation SummarizationSetBy = Automatic

	column IsCsvSource
		dataType: boolean
		isHidden
		lineageTag: b3e20749-dece-4192-b3c8-5b3c84b35c38
		summarizeBy: none
		sourceColumn: IsCsvSource

		annotation SummarizationSetBy = Automatic

	partition '08 XER_ACTVCODE' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("08_xer_actvcode", "t.""actv_code_name"", t.""actv_code_id_key"", t.""actv_code_type_id_key"""),
				    ContractColumns = Record.Field(XerCsvTableContracts, "08_XER_ACTVCODE")[Columns],
				    ModelColumns = List.Combine({ContractColumns, {"IsCsvSource"}}),
				    AthenaFinal = Table.SelectColumns(Source, ContractColumns),
				    AthenaBranch = if XerCsvRouting[HasAthenaProjects] then Table.AddColumn(AthenaFinal, "IsCsvSource", each false, type logical) else Table.AddColumn(fnXerCsvEmptyTable("08_XER_ACTVCODE"), "IsCsvSource", each false, type logical),
				    Combined = if XerCsvRouting[IsActive] then Table.Combine({AthenaBranch, fnXerCsvLoadTable("08_XER_ACTVCODE")}) else AthenaBranch,
				    Final = Table.SelectColumns(Combined, ModelColumns)
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

