table '09 XER_TASKACTV'
	lineageTag: eaa0b48e-3c49-4e66-9990-a5c12154c2a0

	column task_id_key
		dataType: string
		lineageTag: aa832528-9581-4ba1-a2ce-a7252347d9ad
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_id_key
		dataType: string
		lineageTag: 3c2f13a5-99d8-47ac-8ea1-7da85c37deef
		summarizeBy: none
		sourceColumn: actv_code_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_type = related('07 XER_ACTVTYPE'[actv_code_type])
		lineageTag: a8d9dba3-26d5-4ccd-8b1e-3df9a02291ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column actv_code_name = related('08 XER_ACTVCODE'[actv_code_name])
		lineageTag: e3b84066-03c7-40dd-9f53-f2f0247556bb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsCsvSource
		dataType: boolean
		isHidden
		lineageTag: 6b84e805-bcbc-4ce9-8a7d-20a8827685eb
		summarizeBy: none
		sourceColumn: IsCsvSource

		annotation SummarizationSetBy = Automatic

	partition '09 XER_TASKACTV' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("09_xer_taskactv", "t.""actv_code_id_key"", t.""task_id_key"""),
				    ContractColumns = Record.Field(XerCsvTableContracts, "09_XER_TASKACTV")[Columns],
				    ModelColumns = List.Combine({ContractColumns, {"IsCsvSource"}}),
				    AthenaFinal = Table.SelectColumns(Source, ContractColumns),
				    AthenaBranch = if XerCsvRouting[HasAthenaProjects] then Table.AddColumn(AthenaFinal, "IsCsvSource", each false, type logical) else Table.AddColumn(fnXerCsvEmptyTable("09_XER_TASKACTV"), "IsCsvSource", each false, type logical),
				    Combined = if XerCsvRouting[IsActive] then Table.Combine({AthenaBranch, fnXerCsvLoadTable("09_XER_TASKACTV")}) else AthenaBranch,
				    Final = Table.SelectColumns(Combined, ModelColumns)
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

