table '09 XER_TASKACTV'
	lineageTag: eaa0b48e-3c49-4e66-9990-a5c12154c2a0

	column task_id_key
		dataType: string
		lineageTag: aa832528-9581-4ba1-a2ce-a7252347d9ad
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_id_key
		dataType: string
		lineageTag: 3c2f13a5-99d8-47ac-8ea1-7da85c37deef
		summarizeBy: none
		sourceColumn: actv_code_id_key

		annotation SummarizationSetBy = Automatic

	column actv_code_type = related('07 XER_ACTVTYPE'[actv_code_type])
		lineageTag: a8d9dba3-26d5-4ccd-8b1e-3df9a02291ca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column actv_code_name = related('08 XER_ACTVCODE'[actv_code_name])
		lineageTag: e3b84066-03c7-40dd-9f53-f2f0247556bb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition '09 XER_TASKACTV' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("09_xer_taskactv"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"actv_code_id_key", "task_id_key"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

