table '10 XER_CALENDARS'
	lineageTag: 94ce6dcf-9bfd-48f9-b715-089c33d5f05c

	column clndr_id_key
		dataType: string
		lineageTag: 82773d05-0573-4c25-ade7-f4870a47b391
		summarizeBy: none
		sourceColumn: clndr_id_key

		annotation SummarizationSetBy = Automatic

	column clndr_name
		dataType: string
		lineageTag: eac87f0c-8f37-4d3d-b952-4327ce8cdcd1
		summarizeBy: none
		sourceColumn: clndr_name

		annotation SummarizationSetBy = Automatic

	column IsCsvSource
		dataType: boolean
		isHidden
		lineageTag: 50d23983-0d25-49eb-9874-aae5e3ff5c2d
		summarizeBy: none
		sourceColumn: IsCsvSource

		annotation SummarizationSetBy = Automatic

	partition '10 XER_CALENDARS' = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("10_xer_calendar", "t.""clndr_name"", t.""clndr_id_key"""),
				    ContractColumns = Record.Field(XerCsvTableContracts, "10_XER_CALENDAR")[Columns],
				    ModelColumns = List.Combine({ContractColumns, {"IsCsvSource"}}),
				    AthenaFinal = Table.SelectColumns(Source, ContractColumns),
				    AthenaBranch = if XerCsvRouting[HasAthenaProjects] then Table.AddColumn(AthenaFinal, "IsCsvSource", each false, type logical) else Table.AddColumn(fnXerCsvEmptyTable("10_XER_CALENDAR"), "IsCsvSource", each false, type logical),
				    Combined = if XerCsvRouting[IsActive] then Table.Combine({AthenaBranch, fnXerCsvLoadTable("10_XER_CALENDAR")}) else AthenaBranch,
				    Final = Table.SelectColumns(Combined, ModelColumns)
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

