table 12_XER_RSRC
	lineageTag: e4336989-d4b0-42ee-88e3-6b90d448d516

	column rsrc_id_key
		dataType: string
		lineageTag: 1f350a95-5c2d-4644-bfbb-cc98363d613d
		summarizeBy: none
		sourceColumn: rsrc_id_key

		annotation SummarizationSetBy = Automatic

	column def_qty_per_hr
		dataType: string
		lineageTag: d210c000-6734-4030-ba4b-789cfc53306b
		summarizeBy: none
		sourceColumn: def_qty_per_hr

		annotation SummarizationSetBy = Automatic

	partition 12_XER_RSRC = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("12_xer_rsrc"),
				    #"Added Custom" = Table.AddColumn(Source, "ProjectCode", each Text.BeforeDelimiter([filename], "-"), type text),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom",{"def_qty_per_hr", "rsrc_id_key"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

