table 12_XER_RSRC
	lineageTag: e4336989-d4b0-42ee-88e3-6b90d448d516

	column rsrc_id_key
		dataType: string
		lineageTag: 1f350a95-5c2d-4644-bfbb-cc98363d613d
		summarizeBy: none
		sourceColumn: rsrc_id_key

		annotation SummarizationSetBy = Automatic

	column def_qty_per_hr
		dataType: string
		lineageTag: d210c000-6734-4030-ba4b-789cfc53306b
		summarizeBy: none
		sourceColumn: def_qty_per_hr

		annotation SummarizationSetBy = Automatic

	column IsCsvSource
		dataType: boolean
		isHidden
		lineageTag: 7ba8ebef-ded5-43f2-b6cc-88c35fc63833
		summarizeBy: none
		sourceColumn: IsCsvSource

		annotation SummarizationSetBy = Automatic

	partition 12_XER_RSRC = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("12_xer_rsrc", "t.""def_qty_per_hr"", t.""rsrc_id_key"""),
				    ContractColumns = Record.Field(XerCsvTableContracts, "12_XER_RSRC")[Columns],
				    ModelColumns = List.Combine({ContractColumns, {"IsCsvSource"}}),
				    AthenaFinal = Table.SelectColumns(Source, ContractColumns),
				    AthenaBranch = if XerCsvRouting[HasAthenaProjects] then Table.AddColumn(AthenaFinal, "IsCsvSource", each false, type logical) else Table.AddColumn(fnXerCsvEmptyTable("12_XER_RSRC"), "IsCsvSource", each false, type logical),
				    Combined = if XerCsvRouting[IsActive] then Table.Combine({AthenaBranch, fnXerCsvLoadTable("12_XER_RSRC")}) else AthenaBranch,
				    Final = Table.SelectColumns(Combined, ModelColumns)
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

