table 13_XER_TASKRSRC
	lineageTag: bf1a8f41-7390-4182-9b31-8922ded5cf83

	column remain_qty
		dataType: double
		formatString: #,0
		lineageTag: fae86ebb-7fd7-462a-aebf-43ca78c7e576
		summarizeBy: sum
		sourceColumn: remain_qty

		annotation SummarizationSetBy = Automatic

	column target_qty
		dataType: double
		formatString: 0
		lineageTag: 4e626f7f-a921-4fe0-9740-676fda06b751
		summarizeBy: sum
		sourceColumn: target_qty

		annotation SummarizationSetBy = Automatic

	column act_ot_qty
		dataType: double
		formatString: 0
		lineageTag: f2ba6344-3321-4a4d-a329-5b24e454360a
		summarizeBy: sum
		sourceColumn: act_ot_qty

		annotation SummarizationSetBy = Automatic

	column act_reg_qty
		dataType: double
		formatString: 0
		lineageTag: 0d974ad2-89b1-450a-9fbf-75bffa18b2df
		summarizeBy: sum
		sourceColumn: act_reg_qty

		annotation SummarizationSetBy = Automatic

	column act_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c030b0ca-00fa-453e-8294-7e585352df16
		summarizeBy: none
		sourceColumn: act_start_date

		variation Variation
			isDefault
			relationship: d4afbde3-1db7-4172-bbdb-75f9f456bc92
			defaultHierarchy: LocalDateTable_0128c92f-464c-4d3d-b5cd-05a7a97871ca.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column act_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7e6869d-839c-4ce7-98c8-95d2f872d0ff
		summarizeBy: none
		sourceColumn: act_end_date

		variation Variation
			isDefault
			relationship: 3ca0f2b2-b3af-4081-9641-f69ceab4320d
			defaultHierarchy: LocalDateTable_13a38ce0-965a-44e0-899d-fd153e7f4d99.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column restart_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff91f39e-a467-4cde-8077-47b3d8e72064
		summarizeBy: none
		sourceColumn: restart_date

		variation Variation
			isDefault
			relationship: 6fa76ce1-cce2-4840-b9bc-07dddac31fb6
			defaultHierarchy: LocalDateTable_a923ea0f-2aed-4bf1-9520-ea16e8b0ab50.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reend_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd878e99-6b1f-4607-8b55-e756357fdac9
		summarizeBy: none
		sourceColumn: reend_date

		variation Variation
			isDefault
			relationship: 0e26c684-3427-42f3-94b1-cc40f875f474
			defaultHierarchy: LocalDateTable_8674d33e-4d53-4611-b53c-d7da94562d00.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column rsrc_type
		dataType: string
		lineageTag: 7b5eb31a-2494-48d7-ac3b-5c4cae66333d
		summarizeBy: none
		sourceColumn: rsrc_type

		annotation SummarizationSetBy = Automatic

	column rsrc_id_key
		dataType: string
		lineageTag: b1f4a15f-0ada-4b25-b9eb-4eeaa4675556
		summarizeBy: none
		sourceColumn: rsrc_id_key

		annotation SummarizationSetBy = Automatic

	column task_id_key
		dataType: string
		lineageTag: 6b65441c-b7af-48e9-a60a-9c6f5ac3d6aa
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column actual_qty = '13_XER_TASKRSRC'[act_ot_qty]+'13_XER_TASKRSRC'[act_reg_qty]
		formatString: #,0.0
		lineageTag: 738aca5e-1c55-4cfa-b546-3b5c9771913f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column clndr_id_key = related('01 XER_TASK'[calendar_id_key])
		lineageTag: 5cc7c522-488c-40dd-8fcd-5cfb518d2a2c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column rsrc_name = related('12_XER_RSRC'[rsrc_name])
		lineageTag: 327b4de7-bdf9-4017-af32-57b61d01f127
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column status_code = related('01 XER_TASK'[status_code])
		lineageTag: 66107f6b-cdc2-43f2-9bd7-fbc867cb3d6f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column task_code = related('01 XER_TASK'[task_code])
		lineageTag: 25c4ea71-3202-47f8-b86e-c85b3a5b2818
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Data Date' = related('01 XER_TASK'[data_date])
		formatString: dd/mm/yyyy
		lineageTag: 37c64bce-b9c6-47ff-ad51-659c9c5c7bc5
		summarizeBy: none

		variation Variation
			isDefault
			relationship: c2e2203c-0a8d-4b58-acba-29aa3c056195
			defaultHierarchy: LocalDateTable_338125bd-2a91-4452-a2ec-ac77af5aee2e.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column rsrc_short_name = related('12_XER_RSRC'[rsrc_short_name])
		lineageTag: 37da2e04-0af5-44da-bd13-67f4b6ff52d1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Unit = related('12_XER_RSRC'[Unit])
		lineageTag: 6037b3ee-f8b0-4874-a8e3-939340a50613
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column server
		dataType: string
		lineageTag: 5435f20f-0ff3-44b3-b3b3-2d65c10dfef0
		summarizeBy: none
		sourceColumn: server

		annotation SummarizationSetBy = Automatic

	column database
		dataType: string
		lineageTag: e48839ba-b322-45f5-a196-688042883641
		summarizeBy: none
		sourceColumn: database

		annotation SummarizationSetBy = Automatic

	column taskrsrc_id
		dataType: string
		lineageTag: df5785a9-4c50-4b02-b877-87271dffe3be
		summarizeBy: none
		sourceColumn: taskrsrc_id

		annotation SummarizationSetBy = Automatic

	column task_id
		dataType: string
		lineageTag: beb5fe19-a5e6-45c3-aeeb-0e414597e52e
		summarizeBy: none
		sourceColumn: task_id

		annotation SummarizationSetBy = Automatic

	column proj_id
		dataType: string
		lineageTag: 087860c7-0903-4de2-a3d9-83fa73425bcc
		summarizeBy: none
		sourceColumn: proj_id

		annotation SummarizationSetBy = Automatic

	column cost_qty_link_flag
		dataType: string
		lineageTag: c95c6099-baf9-4fe9-af13-378e3dfb0aaa
		summarizeBy: none
		sourceColumn: cost_qty_link_flag

		annotation SummarizationSetBy = Automatic

	column role_id
		dataType: string
		lineageTag: 18b7a6db-3aaa-46b0-ab7f-ce9c40c2c4d5
		summarizeBy: none
		sourceColumn: role_id

		annotation SummarizationSetBy = Automatic

	column acct_id
		dataType: string
		lineageTag: 5025ce84-5766-48ee-813c-002a55eb3e62
		summarizeBy: none
		sourceColumn: acct_id

		annotation SummarizationSetBy = Automatic

	column rsrc_id
		dataType: string
		lineageTag: bf7fe4db-40b5-47fb-a449-193ea6da9b50
		summarizeBy: none
		sourceColumn: rsrc_id

		annotation SummarizationSetBy = Automatic

	column pobs_id
		dataType: string
		lineageTag: eb19e25d-c755-44bf-b35b-45a5a1b18a74
		summarizeBy: none
		sourceColumn: pobs_id

		annotation SummarizationSetBy = Automatic

	column skill_level
		dataType: string
		lineageTag: 2e484cf8-78eb-4380-a3cb-7ce3ecb2e7ca
		summarizeBy: none
		sourceColumn: skill_level

		annotation SummarizationSetBy = Automatic

	column remain_qty_per_hr
		dataType: double
		lineageTag: 5e7c1cea-81b7-4dfe-b2e6-e12d9b84209a
		summarizeBy: sum
		sourceColumn: remain_qty_per_hr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_lag_drtn_hr_cnt
		dataType: double
		lineageTag: e31dd0b6-39ed-40e3-939a-1e40f65421f5
		summarizeBy: sum
		sourceColumn: target_lag_drtn_hr_cnt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_qty_per_hr
		dataType: double
		lineageTag: b6bd504b-818f-4fde-8ead-cfd749d90835
		summarizeBy: sum
		sourceColumn: target_qty_per_hr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column relag_drtn_hr_cnt
		dataType: double
		lineageTag: 36a5c81d-b129-4d31-9a22-62941a862351
		summarizeBy: sum
		sourceColumn: relag_drtn_hr_cnt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ot_factor
		dataType: double
		lineageTag: d1d25c11-ccf8-4bd7-b663-b75476ab0f42
		summarizeBy: sum
		sourceColumn: ot_factor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost_per_qty
		dataType: double
		lineageTag: 175f368a-05df-4f4e-bc4c-9a5c9c808506
		summarizeBy: sum
		sourceColumn: cost_per_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_cost
		dataType: double
		lineageTag: 8d91fbfb-e33a-44c0-987d-d8efeedd1c91
		summarizeBy: sum
		sourceColumn: target_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column act_reg_cost
		dataType: double
		lineageTag: 81baa8e9-d649-40ad-87e9-958eeefac168
		summarizeBy: sum
		sourceColumn: act_reg_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column act_ot_cost
		dataType: double
		lineageTag: d619034e-948d-4aa7-a806-c5e4b693dde3
		summarizeBy: sum
		sourceColumn: act_ot_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column remain_cost
		dataType: double
		lineageTag: 0abafd60-9d80-4ccf-84d8-c81e1ad1c2c5
		summarizeBy: sum
		sourceColumn: remain_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column target_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2a41901-537f-46ed-838a-2b766acb1bb1
		summarizeBy: none
		sourceColumn: target_start_date

		variation Variation
			isDefault
			relationship: fe27d598-2b30-4790-ab94-b88cc96e82e1
			defaultHierarchy: LocalDateTable_7a3188ec-3b10-47a9-8029-efbbe567f8df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column target_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3f05052c-722e-4eb0-b767-bb5fbd42dd54
		summarizeBy: none
		sourceColumn: target_end_date

		variation Variation
			isDefault
			relationship: 2f436058-721b-4cf6-9a2e-04046458acad
			defaultHierarchy: LocalDateTable_48d93f20-8d35-4d5e-a448-f482225635e1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column rem_late_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 590fdfa2-0169-4cec-a8f0-8a74d3dfa327
		summarizeBy: none
		sourceColumn: rem_late_start_date

		variation Variation
			isDefault
			relationship: a2bb1bab-6f53-4d0a-9b52-4a77683ed75c
			defaultHierarchy: LocalDateTable_13030c5f-ab1e-4a1b-8bc7-7f418a45a26c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column rem_late_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e117672b-b140-42e0-9097-10cf00d3fb7f
		summarizeBy: none
		sourceColumn: rem_late_end_date

		variation Variation
			isDefault
			relationship: 5b553e47-cbc6-4e66-8bae-43cd483391b6
			defaultHierarchy: LocalDateTable_ff4bc417-181d-47fb-99d7-937aecb74316.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column rollup_dates_flag
		dataType: string
		lineageTag: f827f470-7228-4804-b7ec-30a47e2779cd
		summarizeBy: none
		sourceColumn: rollup_dates_flag

		annotation SummarizationSetBy = Automatic

	column target_crv
		dataType: string
		lineageTag: d2674608-772a-49b1-929d-1dd5b2548cfc
		summarizeBy: none
		sourceColumn: target_crv

		annotation SummarizationSetBy = Automatic

	column remain_crv
		dataType: string
		lineageTag: 4f01ddae-b6c6-4aa4-821c-cdac6efc072a
		summarizeBy: none
		sourceColumn: remain_crv

		annotation SummarizationSetBy = Automatic

	column actual_crv
		dataType: string
		lineageTag: 8731e534-70cd-49bd-ba29-b56089b17104
		summarizeBy: none
		sourceColumn: actual_crv

		annotation SummarizationSetBy = Automatic

	column ts_pend_act_end_flag
		dataType: string
		lineageTag: 0f258300-6fca-4bfc-a594-dff040edb85d
		summarizeBy: none
		sourceColumn: ts_pend_act_end_flag

		annotation SummarizationSetBy = Automatic

	column guid
		dataType: string
		lineageTag: 54fe6ae6-9c19-4aad-99b2-abdc74ca3836
		summarizeBy: none
		sourceColumn: guid

		annotation SummarizationSetBy = Automatic

	column rate_type
		dataType: string
		lineageTag: 7723cdf7-f48e-4abe-830c-5f584bc42764
		summarizeBy: none
		sourceColumn: rate_type

		annotation SummarizationSetBy = Automatic

	column act_this_per_cost
		dataType: double
		lineageTag: 2086b67c-cf73-43c5-8ae9-85365698e489
		summarizeBy: sum
		sourceColumn: act_this_per_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column act_this_per_qty
		dataType: double
		lineageTag: 9ab67f1c-3815-4025-ae36-2c2f21c4be3a
		summarizeBy: sum
		sourceColumn: act_this_per_qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column curv_id
		dataType: string
		lineageTag: 68b5b9c1-bbd9-4815-8b8b-c21c87792f8c
		summarizeBy: none
		sourceColumn: curv_id

		annotation SummarizationSetBy = Automatic

	column cost_per_qty_source_type
		dataType: string
		lineageTag: be121f3c-8e9f-4c07-bc65-63556244dce6
		summarizeBy: none
		sourceColumn: cost_per_qty_source_type

		annotation SummarizationSetBy = Automatic

	column create_user
		dataType: string
		lineageTag: 919e3795-8881-4778-9988-d5e782e67318
		summarizeBy: none
		sourceColumn: create_user

		annotation SummarizationSetBy = Automatic

	column create_date
		dataType: string
		lineageTag: fb5ca7e0-3685-4d3d-84a7-ccd007eed3ba
		summarizeBy: none
		sourceColumn: create_date

		annotation SummarizationSetBy = Automatic

	column has_rsrchours
		dataType: string
		lineageTag: ed7bb00c-d922-49e9-b52f-1ce6994d5023
		summarizeBy: none
		sourceColumn: has_rsrchours

		annotation SummarizationSetBy = Automatic

	column taskrsrc_sum_id
		dataType: string
		lineageTag: 79efcfe2-322e-4d54-9591-0a93962b191e
		summarizeBy: none
		sourceColumn: taskrsrc_sum_id

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: 720aeced-5965-4fd0-825f-d83f3221a4d3
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: string
		lineageTag: 685b968f-c8b5-46ae-9cb1-318183322e72
		summarizeBy: none
		sourceColumn: refresh_date

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: a506ec54-58d8-4d2d-8d92-ba2610dca30c
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	partition 13_XER_TASKRSRC = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("13_xer_taskrsrc"),
				
				    // Parse date text columns explicitly (Athena returns "2026-01-22 17:00" as text)
				    DateColumns = {"act_start_date", "act_end_date", "restart_date", "reend_date", "target_start_date", "target_end_date", "rem_late_start_date", "rem_late_end_date"},
				    ParsedDates = List.Accumulate(DateColumns, Source, (tbl, col) =>
				        Table.TransformColumns(tbl, {{col, each try Date.From(DateTime.FromText(_)) otherwise null, type date}})
				    ),
				
				    #"Changed Type" = Table.TransformColumnTypes(ParsedDates, {
				        {"remain_qty_per_hr", type number}, {"target_lag_drtn_hr_cnt", type number}, {"target_qty_per_hr", type number},
				        {"act_ot_qty", type number}, {"act_reg_qty", type number}, {"relag_drtn_hr_cnt", type number},
				        {"ot_factor", type number}, {"cost_per_qty", type number}, {"target_cost", type number},
				        {"act_reg_cost", type number}, {"act_ot_cost", type number}, {"remain_cost", type number},
				        {"remain_qty", type number}, {"target_qty", type number}, {"act_this_per_cost", type number},
				        {"act_this_per_qty", type number}
				    }),
				
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "ProjectCode", each Text.BeforeDelimiter([filename], "-"), type text)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

