table 14_XER_UMEASURE
	lineageTag: 9ef23bcb-6604-4071-be24-0f8c46eb7d0d

	column server
		dataType: string
		lineageTag: 54a373b9-341e-4b95-a0c9-39900d1e8981
		summarizeBy: none
		sourceColumn: server

		annotation SummarizationSetBy = Automatic

	column database
		dataType: string
		lineageTag: 1f2718c4-5d4e-4105-bc9f-aaae968d03ac
		summarizeBy: none
		sourceColumn: database

		annotation SummarizationSetBy = Automatic

	column unit_id
		dataType: string
		lineageTag: a383bbe4-eab9-42df-ae0f-133ce4daa953
		summarizeBy: none
		sourceColumn: unit_id

		annotation SummarizationSetBy = Automatic

	column seq_num
		dataType: string
		lineageTag: d2bc669a-1155-41cc-9c79-f1d5549c78f6
		summarizeBy: none
		sourceColumn: seq_num

		annotation SummarizationSetBy = Automatic

	column unit_abbrev
		dataType: string
		lineageTag: 72a8cb50-afd1-416c-a761-02bf2e0b3611
		summarizeBy: none
		sourceColumn: unit_abbrev

		annotation SummarizationSetBy = Automatic

	column unit_name
		dataType: string
		lineageTag: b5dadb53-9fdc-4ec1-a8f0-77b881adb389
		summarizeBy: none
		sourceColumn: unit_name

		annotation SummarizationSetBy = Automatic

	column unit_id_key
		dataType: string
		lineageTag: 104f1512-6c44-4f90-97dd-b08d705862db
		summarizeBy: none
		sourceColumn: unit_id_key

		annotation SummarizationSetBy = Automatic

	column monthupdate
		dataType: string
		lineageTag: f30a8648-10d4-4c1e-8b59-088946961a43
		summarizeBy: none
		sourceColumn: monthupdate

		annotation SummarizationSetBy = Automatic

	column refresh_date
		dataType: string
		lineageTag: dfc9d0e0-1758-44d2-8425-406810b11b42
		summarizeBy: none
		sourceColumn: refresh_date

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		lineageTag: 13ebfe83-92cf-4d93-9088-7543baf04171
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: c204899c-961d-46af-80b2-793c099c2b00
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	partition 14_XER_UMEASURE = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source = fnAthenaSource("14_xer_umeasure"),
				    #"Added Custom" = Table.AddColumn(Source, "ProjectCode", each Text.BeforeDelimiter([filename], "-"), type text)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

