table 15_XER_RESOURCE_DISTRIBUTION
	lineageTag: 87556888-48ae-43af-af95-ce6b18405b46

	column task_id_key
		dataType: string
		lineageTag: 5407ad4a-1bd8-4072-9689-24bffc1fe1d3
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column rsrc_id_key
		dataType: string
		lineageTag: ca303599-4d1a-48f5-a39a-e303665893fd
		summarizeBy: none
		sourceColumn: rsrc_id_key

		annotation SummarizationSetBy = Automatic

	column is_actual
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1b796626-b81e-4475-b92e-0fd47ad7133b
		summarizeBy: none
		sourceColumn: is_actual

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column distribution_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 101cb4d5-156e-45ea-93d7-534ff1d83a3f
		summarizeBy: none
		sourceColumn: distribution_month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column monthly_quantity
		dataType: double
		lineageTag: 53e28e4f-c102-440c-a8ee-2b24b71b0c92
		summarizeBy: sum
		sourceColumn: monthly_quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rsrc_name
		dataType: string
		lineageTag: 81357ff7-ac0c-439e-b536-c68023afaed5
		summarizeBy: none
		sourceColumn: rsrc_name

		annotation SummarizationSetBy = Automatic

	column rsrc_type
		dataType: string
		lineageTag: 08d006e4-73f1-4e1e-bf04-6eba245a8f07
		summarizeBy: none
		sourceColumn: rsrc_type

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: ae960faf-67d8-4533-b3ec-dc512c16e2bd
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: c62bd8a5-5b13-4a6e-8ab0-887addc54dc5
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	column monthly_hours =
			
			VAR Qty = '15_XER_RESOURCE_DISTRIBUTION'[monthly_quantity]
			VAR RsrcType = '15_XER_RESOURCE_DISTRIBUTION'[rsrc_type]
			VAR QtyPerHr = VALUE(LOOKUPVALUE('12_XER_RSRC'[def_qty_per_hr], '12_XER_RSRC'[rsrc_id_key], '15_XER_RESOURCE_DISTRIBUTION'[rsrc_id_key]))
			RETURN
			    IF(
			        RsrcType = "RT_Labor",
			        IF(QtyPerHr <> 0, Qty / QtyPerHr, Qty),
			        Qty
			    )
		formatString: #,0.00
		lineageTag: d2e4f6a8-b0c2-4d6e-8f01-234567890abc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	partition 15_XER_RESOURCE_DISTRIBUTION = m
		mode: import
		queryGroup: XER
		source =
				let
				    Source =
				        fnAthenaSource(
				            "15_xer_resource_distribution",
				            Text.Combine(
				                {
				                    "t.""task_id_key""",
				                    "t.""rsrc_id_key""",
				                    "t.""is_actual""",
				                    "t.""distribution_month""",
				                    "t.""rsrc_name""",
				                    "t.""rsrc_type""",
				                    "t.""unit""",
				                    "t.""monthly_quantity""",
				                    "SPLIT_PART(t.""filename"", '-', 1) AS ""ProjectCode"""
				                },
				                ", "
				            )
				        ),
				    Typed = Table.TransformColumnTypes(Source, {
				        {"distribution_month", type date},
				        {"monthly_quantity", type number}
				    }),
				    ReplacedUnits = Table.ReplaceValue(     // ← NEW STEP
				        Typed,
				        each [unit],
				        each if [rsrc_type] = "RT_Labor" and [unit] = "unit/time"
				             then "hours"
				             else [unit],
				        Replacer.ReplaceValue,
				        {"unit"}
				    ),
				    SelectedColumns = Table.SelectColumns(ReplacedUnits, {  // ← updated reference
				        "task_id_key", "rsrc_id_key", "is_actual", "distribution_month",
				        "rsrc_name", "rsrc_type",
				        "unit", "monthly_quantity", "ProjectCode"
				    })
				in
				    SelectedColumns

	annotation PBI_Id = 67b96e3bda7547809e01d736027b8fa7

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

