table 15_XER_RESOURCE_DISTRIBUTION
	excludeFromModelRefresh
	lineageTag: 87556888-48ae-43af-af95-ce6b18405b46

	column task_id_key
		dataType: string
		lineageTag: 5407ad4a-1bd8-4072-9689-24bffc1fe1d3
		summarizeBy: none
		sourceColumn: task_id_key

		annotation SummarizationSetBy = Automatic

	column rsrc_id_key
		dataType: string
		lineageTag: ca303599-4d1a-48f5-a39a-e303665893fd
		summarizeBy: none
		sourceColumn: rsrc_id_key

		annotation SummarizationSetBy = Automatic

	column clndr_id_key
		dataType: string
		lineageTag: eac86223-0377-4e4c-99e9-af918edb1eab
		summarizeBy: none
		sourceColumn: clndr_id_key

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: f4936ebb-6199-433c-b797-6ce7c666b648
		summarizeBy: none
		sourceColumn: start_date

		variation Variation
			isDefault
			relationship: b4c807dd-39c7-4f94-8538-d8f72a4ce90c
			defaultHierarchy: LocalDateTable_7d1f540e-1d9c-481a-8b9c-57df2e8b74ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc8c712d-ce26-4977-9405-23f284844d10
		summarizeBy: none
		sourceColumn: end_date

		variation Variation
			isDefault
			relationship: e0b10d65-d111-43c5-8ede-e578454a9d82
			defaultHierarchy: LocalDateTable_70091d0d-0a27-4768-a3e3-bdeea2786c8e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column quantity
		dataType: double
		lineageTag: dd617f8c-7ef8-448b-a4e8-37c6387cf905
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column is_actual
		dataType: boolean
		lineageTag: 1b796626-b81e-4475-b92e-0fd47ad7133b
		summarizeBy: none
		sourceColumn: is_actual

		annotation SummarizationSetBy = Automatic

	column status_code
		dataType: string
		lineageTag: c50e42a3-711b-45ed-b523-51a4dcafba3c
		summarizeBy: none
		sourceColumn: status_code

		annotation SummarizationSetBy = Automatic

	column distribution_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 101cb4d5-156e-45ea-93d7-534ff1d83a3f
		summarizeBy: none
		sourceColumn: distribution_month

		variation Variation
			isDefault
			relationship: 629356e8-6c4a-46da-9268-66cd4bd95f67
			defaultHierarchy: LocalDateTable_7621cc0e-f722-4ff3-be50-6d607a231ba9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column month_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 814ba270-2b20-4407-9669-1dbf5618adef
		summarizeBy: none
		sourceColumn: month_start_date

		variation Variation
			isDefault
			relationship: fdd5722d-7bb3-4975-a13d-eebff4725467
			defaultHierarchy: LocalDateTable_4ebabe90-cf58-48c8-a36f-99cc6b685e65.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column month_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c47064f-889b-4cba-b578-83ce73e662b8
		summarizeBy: none
		sourceColumn: month_end_date

		variation Variation
			isDefault
			relationship: 6248db3c-2fe9-40fd-99a5-d7687b412433
			defaultHierarchy: LocalDateTable_0ca9f382-b2de-4063-9664-72e49daad1d1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column month_working_days
		dataType: int64
		formatString: 0
		lineageTag: b9a4cc4b-13fe-4bfd-b692-277d90e2793b
		summarizeBy: sum
		sourceColumn: month_working_days

		annotation SummarizationSetBy = Automatic

	column month_calendar_days
		dataType: int64
		formatString: 0
		lineageTag: 8a5ec838-8793-4c45-b1a6-9c145c054cb7
		summarizeBy: sum
		sourceColumn: month_calendar_days

		annotation SummarizationSetBy = Automatic

	column monthly_quantity
		dataType: double
		lineageTag: 53e28e4f-c102-440c-a8ee-2b24b71b0c92
		summarizeBy: sum
		sourceColumn: monthly_quantity

		annotation SummarizationSetBy = Automatic

	column task_code
		dataType: string
		lineageTag: 1f578f35-4eea-49a9-8c5c-5d12b55211cc
		summarizeBy: none
		sourceColumn: task_code

		annotation SummarizationSetBy = Automatic

	column rsrc_short_name
		dataType: string
		lineageTag: c46e7acc-270f-4351-84f6-549025dc5037
		summarizeBy: none
		sourceColumn: rsrc_short_name

		annotation SummarizationSetBy = Automatic

	column rsrc_name
		dataType: string
		lineageTag: 81357ff7-ac0c-439e-b536-c68023afaed5
		summarizeBy: none
		sourceColumn: rsrc_name

		annotation SummarizationSetBy = Automatic

	column rsrc_type
		dataType: string
		lineageTag: 08d006e4-73f1-4e1e-bf04-6eba245a8f07
		summarizeBy: none
		sourceColumn: rsrc_type

		annotation SummarizationSetBy = Automatic

	column is_working_day_dist
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e8b4aaac-527b-4ab1-8350-08ed76f1f62b
		summarizeBy: none
		sourceColumn: is_working_day_dist

		annotation SummarizationSetBy = Automatic

	partition 15_XER_RESOURCE_DISTRIBUTION = m
		mode: import
		queryGroup: XER
		source = ```
				let
				    // ── Reference staging queries ──
				    TaskRsrc = Staging_TaskRsrc,
				    Task = Staging_Task,
				    CalStandard = Staging_Calendar_Standard,
				    CalExceptions = Staging_Calendar_Exceptions,
				
				    // ══════════════════════════════════════════════════════════════
				    // PHASE 1: Build narrow working table
				    // ══════════════════════════════════════════════════════════════
				
				    TaskLookup = Table.SelectColumns(Task, {"task_id_key", "status_code", "calendar_id_key", "data_date"}),
				    TaskRsrcJoined = Table.NestedJoin(TaskRsrc, {"task_id_key"}, TaskLookup, {"task_id_key"}, "TaskData", JoinKind.LeftOuter),
				    TaskRsrcExpanded = Table.ExpandTableColumn(TaskRsrcJoined, "TaskData",
				        {"status_code", "calendar_id_key", "data_date"},
				        {"_status_code", "_clndr_id_key", "_data_date"}
				    ),
				
				    Actuals = Table.SelectRows(TaskRsrcExpanded, each
				        List.Contains({"Complete", "In Progress"}, [_status_code])
				        and ([act_ot_qty] + [act_reg_qty]) > 0
				        and [act_start_date] <> null
				    ),
				    ActualsNarrow = Table.SelectColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Table.AddColumn(Actuals,
				                        "start_date", each Date.From([act_start_date]), type date),
				                    "end_date", each if [_status_code] = "Complete" then Date.From([act_end_date]) else Date.From([_data_date]), type date),
				                "quantity", each [act_ot_qty] + [act_reg_qty], type number),
				            "is_actual", each true, type logical),
				        {"task_id_key", "rsrc_id_key", "_clndr_id_key", "start_date", "end_date", "quantity", "is_actual", "_status_code"}
				    ),
				
				    Remaining = Table.SelectRows(TaskRsrcExpanded, each
				        List.Contains({"Not Started", "In Progress"}, [_status_code])
				        and [remain_qty] > 0
				        and [restart_date] <> null and [reend_date] <> null
				    ),
				    RemainingNarrow = Table.SelectColumns(
				        Table.AddColumn(
				            Table.AddColumn(
				                Table.AddColumn(
				                    Table.AddColumn(Remaining,
				                        "start_date", each Date.From([restart_date]), type date),
				                    "end_date", each Date.From([reend_date]), type date),
				                "quantity", each [remain_qty], type number),
				            "is_actual", each false, type logical),
				        {"task_id_key", "rsrc_id_key", "_clndr_id_key", "start_date", "end_date", "quantity", "is_actual", "_status_code"}
				    ),
				
				    Combined = Table.Combine({ActualsNarrow, RemainingNarrow}),
				    ValidRows = Table.SelectRows(Combined, each [start_date] <> null and [end_date] <> null and [start_date] <= [end_date]),
				
				    // ══════════════════════════════════════════════════════════════
				    // PHASE 2: Calendar lookups
				    // ══════════════════════════════════════════════════════════════
				
				    StandardDaysByCalendar = Table.Group(CalStandard, {"clndr_id_key"},
				        {{"WorkDayNums", each List.Buffer(List.Distinct([day_of_week_num])), type list}}
				    ),
				
				    Holidays = Table.Group(
				        Table.SelectRows(CalExceptions, each [working_day_int] = 0),
				        {"clndr_id_key"},
				        {{"HolidayDates", each List.Buffer(List.Distinct([date])), type list}}
				    ),
				    ExtraWork = Table.Group(
				        Table.SelectRows(CalExceptions, each [working_day_int] = 1),
				        {"clndr_id_key"},
				        {{"ExtraWorkDates", each List.Buffer(List.Distinct([date])), type list}}
				    ),
				
				    // Formula-based working day count: arithmetic for standard weeks,
				    // iterate only exceptions. Replaces day-by-day loop.
				    CountWorkingDays = (periodStart as date, periodEnd as date, workDayNums as list, holidayDates as list, extraWorkDates as list) as number =>
				        let
				            totalDays = Duration.Days(periodEnd - periodStart) + 1,
				            fullWeeks = Number.IntegerDivide(totalDays, 7),
				            remainderDays = Number.Mod(totalDays, 7),
				
				            workDaysPerWeek = List.Count(workDayNums),
				            baseFromFullWeeks = fullWeeks * workDaysPerWeek,
				
				            startDow = Date.DayOfWeek(periodStart, Day.Monday) + 1,
				            remainderWorkDays = List.Count(
				                List.Select({0..remainderDays - 1}, (offset) =>
				                    let
				                        dow = Number.Mod(startDow + offset - 1, 7) + 1
				                    in
				                        List.Contains(workDayNums, dow)
				                )
				            ),
				
				            standardTotal = baseFromFullWeeks + remainderWorkDays,
				
				            holidaysInRange = List.Select(holidayDates, each _ >= periodStart and _ <= periodEnd),
				            holidayAdjust = List.Count(
				                List.Select(holidaysInRange, (d) =>
				                    let dow = Date.DayOfWeek(d, Day.Monday) + 1
				                    in List.Contains(workDayNums, dow)
				                )
				            ),
				
				            extrasInRange = List.Select(extraWorkDates, each _ >= periodStart and _ <= periodEnd),
				            extraAdjust = List.Count(
				                List.Select(extrasInRange, (d) =>
				                    let dow = Date.DayOfWeek(d, Day.Monday) + 1
				                    in not List.Contains(workDayNums, dow)
				                )
				            ),
				
				            result = standardTotal - holidayAdjust + extraAdjust
				        in
				            if result < 0 then 0 else result,
				
				            
				    // ── Merge calendar data ──
				    WithCalendarData = Table.ExpandTableColumn(
				        Table.NestedJoin(ValidRows, {"_clndr_id_key"}, StandardDaysByCalendar, {"clndr_id_key"}, "StdData", JoinKind.LeftOuter),
				        "StdData", {"WorkDayNums"}, {"_WorkDayNums"}
				    ),
				    WithHolidays = Table.ExpandTableColumn(
				        Table.NestedJoin(WithCalendarData, {"_clndr_id_key"}, Holidays, {"clndr_id_key"}, "HolData", JoinKind.LeftOuter),
				        "HolData", {"HolidayDates"}, {"_HolidayDates"}
				    ),
				    WithExtras = Table.ExpandTableColumn(
				        Table.NestedJoin(WithHolidays, {"_clndr_id_key"}, ExtraWork, {"clndr_id_key"}, "ExtData", JoinKind.LeftOuter),
				        "ExtData", {"ExtraWorkDates"}, {"_ExtraWorkDates"}
				    ),
				    CleanedData = Table.TransformColumns(WithExtras, {
				        {"_WorkDayNums", each if _ = null then {} else _, type list},
				        {"_HolidayDates", each if _ = null then {} else _, type list},
				        {"_ExtraWorkDates", each if _ = null then {} else _, type list}
				    }),
				
				    // ══════════════════════════════════════════════════════════════
				    // PHASE 3: Month expansion + distribution
				    // ══════════════════════════════════════════════════════════════
				
				    Distributed = Table.AddColumn(CleanedData, "MonthlyRows", each
				        let
				            sd = [start_date],
				            ed = [end_date],
				            qty = [quantity],
				            wdNums = [_WorkDayNums],
				            holDates = [_HolidayDates],
				            extDates = [_ExtraWorkDates],
				            firstMonth = #date(Date.Year(sd), Date.Month(sd), 1),
				            lastMonth = #date(Date.Year(ed), Date.Month(ed), 1),
				            monthCount = (Date.Year(lastMonth) - Date.Year(firstMonth)) * 12
				                         + Date.Month(lastMonth) - Date.Month(firstMonth) + 1,
				
				            months = List.Transform({0..monthCount - 1}, (i) =>
				                let
				                    cmStart = Date.AddMonths(firstMonth, i),
				                    cmEnd = Date.EndOfMonth(cmStart),
				                    periodStart = List.Max({cmStart, sd}),
				                    periodEnd = List.Min({cmEnd, ed}),
				                    mWD = CountWorkingDays(periodStart, periodEnd, wdNums, holDates, extDates),
				                    mCD = Duration.Days(periodEnd - periodStart) + 1
				                in
				                    [distribution_month = cmStart, month_start_date = periodStart, month_end_date = periodEnd,
				                     month_working_days = mWD, month_calendar_days = mCD]
				            ),
				
				            totalWD = List.Sum(List.Transform(months, each [month_working_days])),
				            totalCD = List.Sum(List.Transform(months, each [month_calendar_days])),
				            useWD = totalWD > 0,
				
				            distributed = List.Select(
				                List.Transform(months, (m) =>
				                    let
				                        mq = if useWD
				                             then m[month_working_days] * qty / totalWD
				                             else m[month_calendar_days] * qty / totalCD
				                    in
				                        [distribution_month = m[distribution_month],
				                         month_start_date = m[month_start_date],
				                         month_end_date = m[month_end_date],
				                         month_working_days = m[month_working_days],
				                         month_calendar_days = m[month_calendar_days],
				                         monthly_quantity = mq,
				                         is_working_day_dist = useWD]
				                ),
				                each [monthly_quantity] > 0
				            )
				        in
				            distributed,
				        type list
				    ),
				
				    PreExpand = Table.RemoveColumns(Distributed, {"_WorkDayNums", "_HolidayDates", "_ExtraWorkDates"}),
				
				    Expanded = Table.ExpandListColumn(PreExpand, "MonthlyRows"),
				    ExpandedRecords = Table.ExpandRecordColumn(Expanded, "MonthlyRows",
				        {"distribution_month", "month_start_date", "month_end_date", "month_working_days",
				         "month_calendar_days", "monthly_quantity", "is_working_day_dist"}
				    ),
				
				    // ══════════════════════════════════════════════════════════════
				    // PHASE 4: Join descriptive columns LAST
				    // ══════════════════════════════════════════════════════════════
				
				    TaskDescriptive = Table.SelectColumns(Staging_Task, {"task_id_key", "task_code"}),
				    WithTaskDesc = Table.ExpandTableColumn(
				        Table.NestedJoin(ExpandedRecords, {"task_id_key"}, TaskDescriptive, {"task_id_key"}, "_TD", JoinKind.LeftOuter),
				        "_TD", {"task_code"}, {"task_code"}
				    ),
				
				    WithRsrcDesc = Table.ExpandTableColumn(
				        Table.NestedJoin(WithTaskDesc, {"rsrc_id_key"}, Staging_Rsrc, {"rsrc_id_key"}, "_RD", JoinKind.LeftOuter),
				        "_RD", {"rsrc_short_name", "rsrc_name", "rsrc_type"}
				    ),
				
				    Renamed = Table.RenameColumns(WithRsrcDesc, {{"_clndr_id_key", "clndr_id_key"}, {"_status_code", "status_code"}}),
				
				    FinalColumns = Table.SelectColumns(Renamed,
				        {"task_id_key", "rsrc_id_key", "clndr_id_key", "start_date", "end_date", "quantity", "is_actual", "status_code",
				         "task_code", "distribution_month", "month_start_date", "month_end_date", "month_working_days", "month_calendar_days",
				         "monthly_quantity", "is_working_day_dist",
				         "rsrc_short_name", "rsrc_name", "rsrc_type"}
				    ),
				
				    FinalTyped = Table.TransformColumnTypes(FinalColumns, {
				        {"start_date", type date}, {"end_date", type date},
				        {"distribution_month", type date}, {"month_start_date", type date}, {"month_end_date", type date},
				        {"quantity", type number}, {"monthly_quantity", type number},
				        {"month_working_days", Int64.Type}, {"month_calendar_days", Int64.Type},
				        {"is_actual", type logical}, {"is_working_day_dist", type logical}
				    })
				in
				    FinalTyped
				```

	annotation PBI_Id = 67b96e3bda7547809e01d736027b8fa7

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

