table 'Dynamic Titles & Formatting'
	lineageTag: 90e746fb-9a32-4cfc-b7b2-3d277b4be9cc

	measure ProjectTitle = ```
			
			SELECTEDVALUE('01 XER_TASK'[ProjectName], "N/A") & " : " & 
			FORMAT([CurrentDate], "MMMM yyyy") & " Update vs " & 
			FORMAT([BL Month Update], "MMMM yyyy") & " Baseline"
			```
		lineageTag: 470d1c51-6bde-4f63-be0c-866808e36c21

	measure SelectedTitle =
			
			VAR SelectedProject = SELECTEDVALUE(Project_Dimension[Project])
			VAR SelectedMonth = SELECTEDVALUE(CurrentDate[UpdateDate]) // This captures the selected month (likely a date value)
			
			RETURN
			    IF(
			        ISBLANK(SelectedProject),
			        "Please select a project and available month.",
			        -- Else (a project is selected)
			        IF(
			            ISBLANK(SelectedMonth),
			            "Selected Project: " & SelectedProject & " (No month selected)",
			            "Selected Project: " & SelectedProject & " - " & FORMAT(SelectedMonth, "MMMM YYYY") // Applied formatting here
			        )
			    )
		lineageTag: 11f7d509-f31a-45b5-b26e-94f5d33c1864

	measure PeriodLabel =
			
			VAR PreviousDateFormatted = FORMAT([PreviousDataDate], "dd/mm/yyyy")
			VAR CurrentDateFormatted = FORMAT([CurrentDataDate], "dd/mm/yyyy")
			RETURN
			    IF(
			        ISBLANK([PreviousDataDate]),
			        "Period: " & CurrentDateFormatted,
			        "Period: " & PreviousDateFormatted & " to " & CurrentDateFormatted
			    )
		lineageTag: cf7d5d51-f0e2-4d0b-9c39-85421591e6ac

	measure 'Data Date Title' = "Data Date : " & FORMAT([CurrentDataDate], "dd-MM-yyyy")
		lineageTag: f09d3783-1842-42b2-a094-a2b44eb60971

	measure SelectedFile =
			
			VAR SelectedProject = SELECTEDVALUE('01 XER_TASK'[FileName])
			
			RETURN
			    IF(
			        ISBLANK(SelectedProject),
			        "Please select a project and available month.",
			        SelectedProject
			    )
		lineageTag: 2b885338-2d96-4094-b37d-c45f4261d77d

	measure 'Resource Selected' =
			
			VAR _SelectedName = SELECTEDVALUE ( '15_XER_RESOURCE_DISTRIBUTION'[rsrc_name] )
			VAR _SelectedType = SELECTEDVALUE ( '15_XER_RESOURCE_DISTRIBUTION'[rsrc_type] )
			VAR _SelectedUnit = SELECTEDVALUE ( '15_XER_RESOURCE_DISTRIBUTION'[unit] )
			
			VAR _DisplayUnit =
			    IF (
			        _SelectedType = "RT_Labor",
			        "Hours",
			        _SelectedUnit
			    )
			
			VAR _UnitString =
			    IF (
			        NOT ISBLANK ( _DisplayUnit ),
			        " (Unit: " & _DisplayUnit & ")",
			        ""
			    )
			
			RETURN
			    IF (
			        ISBLANK ( _SelectedName ),
			        "Multiple Resources Selected" & _UnitString,
			        "Selected Resource: " & _SelectedName & _UnitString
			    )
		lineageTag: 963b9af2-1f55-43ce-9f49-2a45a2c5299d

	measure Behind_Schedule_Flag =
			
			VAR ActualFinish = [Percentage_Actual_Finish]
			VAR BaselineFinish = [Percentage_Baseline_Finish]
			
			RETURN
			    IF(
			        ActualFinish < BaselineFinish,
			        1,  // Behind Schedule
			        0   // On or Ahead of Schedule
			    )
		formatString: 0
		lineageTag: d1687793-de42-4fe0-bac2-dc2bf408a6fd

	measure SummaryTitle = ```
			
			"Project Summary : " & 
			FORMAT([CurrentDate], "MMMM yyyy")
			```
		lineageTag: e0828f98-750d-41e7-ad5c-b1f4cd33f32d

	measure 'Datalake Symbol' = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64' width='64' height='64'><path d='M 4,48 Q 16,44 28,48 T 52,48 T 60,48 L 60,60 L 4,60 Z' fill='%23e1f5fe' /><path d='M 0,52 Q 12,49 24,52 T 48,52 T 64,52 L 64,60 L 0,60 Z' fill='%230288d1' /><path d='M 18,15 L 18,22 C 18,26 46,26 46,22 L 46,15 Z' fill='%23b3e5fc' stroke='%2301579b' stroke-width='2' /><ellipse cx='32' cy='15' rx='14' ry='5' fill='%23e1f5fe' stroke='%2301579b' stroke-width='2' /><path d='M 18,26 L 18,33 C 18,37 46,37 46,33 L 46,26 Z' fill='%2381d4fa' stroke='%2301579b' stroke-width='2' /><ellipse cx='32' cy='26' rx='14' ry='5' fill='%23b3e5fc' stroke='%2301579b' stroke-width='2' /><path d='M 18,37 L 18,44 C 18,48 46,48 46,44 L 46,37 Z' fill='%234fc3f7' stroke='%2301579b' stroke-width='2' /><ellipse cx='32' cy='37' rx='14' ry='5' fill='%2381d4fa' stroke='%2301579b' stroke-width='2' /></svg>"
		lineageTag: b35a74ef-bc11-4f33-8a03-6e7bfa56a2ad

	measure 'Datalake Refresh Note' = ```
			
			VAR RawText = MAX('dbo_userpermission'[refresh_date])
			VAR DatePart = IFERROR(DATEVALUE(LEFT(RawText, 10)), DATE(2026, 6, 25))
			VAR TimePart = IFERROR(TIMEVALUE(MID(RawText, 12, 8)), TIME(12, 0, 0))
			VAR UtcDateTime = DatePart + TimePart
			VAR Yr = YEAR(UtcDateTime)
			VAR Oct1 = DATE(Yr, 10, 1)
			VAR OctSunday = Oct1 + MOD(8 - WEEKDAY(Oct1, 2), 7)
			VAR Apr1 = DATE(Yr, 4, 1)
			VAR AprSunday = Apr1 + MOD(8 - WEEKDAY(Apr1, 2), 7)
			VAR MonthNum = MONTH(UtcDateTime)
			VAR OffsetHours = 
			    IF(
			        MonthNum > 10 || MonthNum < 4 || (MonthNum = 10 && UtcDateTime >= OctSunday) || (MonthNum = 4 && UtcDateTime < AprSunday),
			        11,
			        10
			    )
			VAR LocalTime = UtcDateTime + (OffsetHours / 24)
			VAR TzSuffix = IF(OffsetHours = 11, "AEDT", "AEST")
			RETURN
			    IF(
			        ISBLANK(RawText),
			        "Last Refreshed: N/A",
			        "Last Refreshed: " & FORMAT(LocalTime, "dd/mm/yyyy hh:mm:ss AM/PM") & " " & TzSuffix
			    )
			```
		lineageTag: a1b2c3d4-5e6f-7a8b-9c0d-ef123456789a

	partition 'Dynamic Titles & Formatting' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

