table UserPermission
	lineageTag: 16634cc5-2311-4145-a599-5cdf61ee38c3

	column UserPrincipalName
		dataType: string
		lineageTag: c3c85e97-2c51-4e64-8422-afacb8a1e253
		summarizeBy: none
		sourceColumn: UserPrincipalName

		annotation SummarizationSetBy = Automatic

	column 'All Access'
		dataType: int64
		formatString: 0
		lineageTag: b5fa43c6-608d-4c99-aa54-71ef34c921a6
		summarizeBy: sum
		sourceColumn: All Access

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 971f163d-3d32-471b-85be-a7067eeede29
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column ExternalUserPrincipalName
		dataType: string
		lineageTag: a8f99c2f-1776-4928-a86a-18e57785e927
		summarizeBy: none
		sourceColumn: ExternalUserPrincipalName

		annotation SummarizationSetBy = Automatic

	column ProjectCode
		dataType: string
		lineageTag: d84b84a7-f786-4fdd-9c8b-0665e48ac0ff
		summarizeBy: none
		sourceColumn: ProjectCode

		annotation SummarizationSetBy = Automatic

	partition UserPermission = m
		mode: import
		queryGroup: XER
		source =
				let
				    Permissions = SharePoint.Contents(SharePointSite, [ApiVersion = 15])
				        { [Name="Documents"] }[Content]
				        { [Name="P6"] }[Content]
				        { [Name="Programme"] }[Content],
				    #"Permissions xlsx" = Permissions{[Name="Permissions.xlsx"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"Permissions xlsx"),
				    UserPermission_Table1 = #"Imported Excel Workbook"{[Item="UserPermission",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(UserPermission_Table1,{{"All Access", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"UserPrincipalName", "All Access", "State", "ExternalUserPrincipalName", "ProjectCode"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

